### ISSUE TITLE
[BUG] Crash report after unlocking the phone and with Gramophone not currently used

### ISSUE THREAD

**Issue by Porkepix** [FoedusProgramme/Gramophone#100]
**Describe the bug**

A crash report poped at screen after unlocking the phone. Gramophone wasn't in use.

**To Reproduce**

No STR

**Expected behavior**

No crash. Also, the crash report didn't allow to copy the text, which would be a nice thing: I can only provide the screenshot of the crash.

**Screenshots**

<details>
<summary>
Screenshot
</summary>

![Screenshot_20240223-095017](https://github.com/AkaneTan/Gramophone/assets/709500/dc109d92-1870-4266-837c-561005e442c5)

</details>

**Smartphone (please complete the following information):**
 - Device: Xperia XZ
 - OS: Android 8.0 (Oreo)
 - App Version: 1.4.0.1.c72ab5 (build from another issue)

**Comment by nift4** [comment]
1. The crash should be fixed now, thanks
2. The crash dialog automatically copies the text into your clipboard :)

**Comment by Porkepix** [comment]
>     2. The crash dialog automatically copies the text into your clipboard :)

Nothing shows it or inform the user of it, I think. Plus in case the user put this aside and want to get back at it and copy it because clipboard was overwritten, they can't. A button to copy or allow the user to select the text would be a nice addition I think (aside informing the user that it's been copied to the clipboard)

**Comment by nift4** [comment]
Thanks, it has been adressed
