### ISSUE TITLE
Relocate buttons & improve icons

### ISSUE THREAD

**Issue by Donkey-Doug** [FoedusProgramme/Gramophone#101]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when buttons are all over the place.

**Describe the solution you'd like**
A clear and concise description of what you want to happen: Relocate buttons to top row. In my opinion the shuffle and play buttons should be removed. Also, the filter icon is shown, but the functionality is sorting. Finally, I cannot press the filter/sort button easily, because it grabs the scroll-handle instead.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered: -

**Additional context**
Add any other context or screenshots about the feature request here:

![Screenshot_20240223-234755_Gramophone_1](https://github.com/AkaneTan/Gramophone/assets/50382414/bb808f3d-1ab8-4349-986a-ff87388c125d)

**Comment by AkaneTan** [comment]
Topappbar has buttons related to app-wide operations, meanwhile the item indicator (or in code as general decorator) serves list-wide operations. I don't think anything's wrong with current UX/UI.
