### ISSUE TITLE
[BUG] White app bar

### ISSUE THREAD

**Issue by derdilla** [FoedusProgramme/Gramophone#112]
**Describe the bug**
The collapsed app bar becomes white on Mi 9 in dark mode. It looses allot of contrast and becomes hard to read.

**To Reproduce**
1. Go to main screen (or any other screen with an app bar that allows scrolling down)
2. Scroll down untill app bar is bompact
3. See error

**Expected behavior**
The app bar should have enough contrast for the text to be readable.

**Screenshots**
![IMG_20240225_093852.jpg](https://github.com/AkaneTan/Gramophone/assets/82763757/b3958a83-2ed0-40c8-a681-e8b467431eae)

**Smartphone (please complete the following information):**
 - Device: Xaiomi Mi 9
 - OS: Android 10; MIUI Global 12.0.5
 - App Version: 1.0.4.1.9cd07e

**Additional context**
MIUI tries to automatically adjust colors of apps that it thinks are in light mode. It seems like the app bar doesn't properly declare that it's dark by default to the system.
Curiously when I set the app to light mode, it stays dark (although a different shade) and the bug persists.

Edit: works fine on the crash screen

**Comment by nift4** [comment]
[Gramophone-1.0.4.1.f5848e-release.apk.zip](https://github.com/AkaneTan/Gramophone/files/14397293/Gramophone-1.0.4.1.f5848e-release.apk.zip)
The issue should be resolved in this beta version, let me know if its fixed

**Comment by derdilla** [comment]
Thanks, I can confirm that the fix works.
