### ISSUE TITLE
[BUG] Gramophone cannot find music from the SD Card

### ISSUE THREAD

**Issue by Ashvith10** [FoedusProgramme/Gramophone#126]
**Describe the bug**
Right now, Gramophone can only read music from the Internal Storage - it does not matter if it's not in "Music" or the root of the Internal Folder. This app cannot read from the SD Card.

**To Reproduce**
1. Launch Gramophone app
2. Click on '⋮' (Kebab menu)
3. Click on 'Refresh'
4. Only music in Internal Storage is visible

**Expected behavior**
Music from the SD Card should also be indexed.

**Screenshots**
Not applicable

**Smartphone (please complete the following information):**
 - Device: realme 5 Pro (RMX1971)
 - OS: Android 14 (Custom ROM)
 - App Version: 1.0.4.1.9cd07e

**Additional context**
Not applicable

**Comment by nift4** [comment]
can other players see the music?

**Comment by Ashvith10** [comment]
This is a weird bug. I am not sure what I did, but after playing with the permissions in the Phonograph Plus app, all the other app started working (Gramophone as well as Auxio)? From what I understand, maybe "that" (I'm not sure which one, unfortunately, but I could try playing around) particular storage permission needs to be added as a popup in Gramophone.

**Comment by nift4** [comment]
It is likely that playing with the storage permissions, android re-scanned the files and found them. You can use https://f-droid.org/packages/com.gmail.jerickson314.sdscanner/ to reliably trigger that again. Let me know if you experience further issues.
