### ISSUE TITLE
项目拉取下来编译，抛出[Fatal Error] kotlin-build-tools-impl-2.0.0-Beta4.pom:2:1: ǰ���в����������ݡ�异常

### ISSUE THREAD

**Issue by sianqin** [FoedusProgramme/Gramophone#127]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - App Version: [e.g. 22]

**Additional context**

**Comment by AkaneTan** [comment]
https://github.com/AkaneTan/Gramophone?tab=readme-ov-file#set-up-package-type

**Comment by AkaneTan** [comment]
也可能是网络问题
