### ISSUE TITLE
非常非常喜欢(Wear OS)

### ISSUE THREAD

**Issue by on6hz** [FoedusProgramme/Gramophone#129]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
If headphone connected then resume playback.

**Describe alternatives you've considered**
I've not.

**Additional context**
Addditionally a playback delay and volume resume gradually upon the headphone connection.
Adddditionally a more or less Wear OS UI optimization.

主要是来表达喜爱，功能并不急需，只是在手表上在用，没有在手机上用，谢谢

**Comment by AkaneTan** [comment]
Issue 是用来提交问题的，~~如果想表达感谢可以私信我。~~
关于WearOS改进的问题，请另开issue。
