### ISSUE TITLE
[FR] Add default music player feature

### ISSUE THREAD

**Issue by weird-budy** [FoedusProgramme/Gramophone#136]
Please add an option to make it default music player.
Samsung phones has only the voice recorder to play audio 
.

**Comment by SleepyScribe** [comment]
Having the same issue on Pixel 7 Pro. Had to move to Auxio until this is available, as I run a search based launcher and I can't set my music to open in Gramophone by default. It doesn't seem to register as a music player.

**Comment by weird-budy** [comment]
True. But what is auxio. Can you suggest an open source music player that doesn't have this problem

**Comment by SleepyScribe** [comment]
@weird-budy Auxio is open source and works as a default player. You can get it right on F-Droid.

**Comment by nift4** [comment]
This has been added
