### ISSUE TITLE
Track sorting within Genre Tab [BUG]

### ISSUE THREAD

**Issue by Lexo15** [FoedusProgramme/Gramophone#145]
In version 1.02 it was working perfectly but in version 1.04 this glitch appeared.
In **Genres** Tab when I select a particular Genre, for example, "Rock", I'm shown various tracks from various artists in shuffled order. Well let it be, this is not a problem.
Then I press the 3 lines in top right corner and choose "Album". The Albums are sorted in the correct order: Artist>Album
However, the tracks inside each album are not in the correct order: they are sorted alphabetically, while they should be sorted according to their track numbers.

For example, Metallica's 1991 album should have the following track listing (correct):
Enter Sandman
Sad But True
Holier Than Thou
The Unforgiven
Wherever I May Roam
Don’t Tread on Me
Through the Never
Nothing Else Matters
Of Wolf and Man
The God That Failed
My Friend of Misery
The Struggle Within

However, here's what I'm given in version 1.04 (incorrect):
Don’t Tread on Me
Enter Sandman
Holier Than Thou
My Friend of Misery
Nothing Else Matters
Of Wolf and Man
Sad But True
The God That Failed
The Struggle Within
The Unforgiven
Through the Never
Wherever I May Roam

**Comment by nift4** [comment]
This will probably be addressed in 1.0.6 or 1.1.0
