### ISSUE TITLE
Option to remove favourites playlist from MediaStore

### ISSUE THREAD

**Issue by hofheinz** [FoedusProgramme/Gramophone#146]
**Is your feature request related to a problem? Please describe.**
Gramophone initially creates a new playlist “gramophone_favourites” (or “Favourites” in Gramophone itself) in Android's MediaStore. There appears to be no way to get rid of this playlist under Android >=12 (short of rooting the phone or a factory reset). Other apps apparently cannot remove playlists owned by Gramophone, and Android provides no way to edit/reset MediaStore playlists. This can be annoying, though, as this playlist shows up in other music player apps, even after uninstalling Gramophone. Now this may be viewed as an Android shortcoming, but MediaStore playlists are deprecated, and this is unlikely to be fixed at this point. Also, subjectively, it would seem nicer if Gramophone provided a way to clean up things it added.

**Describe the solution you'd like**
Please consider having an option to clear/not use gramophone_favorites, or to not store this list in the MediaStore.

**Comment by nift4** [comment]
Can't you delete the .m3u file in Music?

**Comment by hofheinz** [comment]
Oh.

I feel a bit stupid now, but yes, that appears to be entirely possible (and removes the MediaStorage playlist). (In case somebody stumbles across this: apparently MediaStorage playlists are stored as .m3u files in the Music directory, so it's possible to “manage” these files with file managers/editors.) But might I remark what a surprising API this is.

In any case, thanks! I guess this makes the FR probably useless, so I'll close.

**Comment by nift4** [comment]
The UI for creating, editing and deleting playlists is still WIP, but it will be possible directly from Gramophone in the future.

**Comment by hofheinz** [comment]
(To clarify: I did mean that the Android MediaStorage API with “surprising”, not anything related to Gramophone.)

In any case: it's great that Gramophone will have a more flexible UI for playlists in the future! This is a very sleek and useful music player, and I only got to this while trying out a number of music players. Thank you for your work on this!

**Comment by PrivacyFriendlyMuffins** [comment]
> (In case somebody stumbles across this: apparently MediaStorage playlists are stored as .m3u files in the Music directory, so it's possible to “manage” these files with file managers/editors.)

Just an FYI: I am one of those people who had this exact same issue, and so I thank you for providing the solution in your comment. It helped! :)
