### ISSUE TITLE
Equaliser not working properly

### ISSUE THREAD

**Issue by prajwalpatil2204** [FoedusProgramme/Gramophone#147]
**Screenshots**
![Screenshot_2024-03-30-17-04-20-022_com miui audioeffect](https://github.com/AkaneTan/Gramophone/assets/40023187/75132668-7ff6-41cd-a46a-02c5cebcdb47)
After changing Fx still equalizer is working on FX Booster
![Screenshot_2024-03-30-17-04-26-543_com miui audioeffect](https://github.com/AkaneTan/Gramophone/assets/40023187/e1271d41-a90e-459d-8c0c-e621020af065)

 - Device: [Redmi note 10 ]
 - OS: [Android 12]
 - App Version: 1.0.4.1

**Comment by nift4** [comment]
It works here.

Because you provided literally no information at all, that is all I can answer.
