### ISSUE TITLE
Equalizer not working properly. 

### ISSUE THREAD

**Issue by prajwalpatil2204** [FoedusProgramme/Gramophone#148]
**Screenshots**
![Screenshot_2024-03-30-17-04-20-022_com miui audioeffect](https://github.com/AkaneTan/Gramophone/assets/40023187/f9544c42-33d5-4504-a0d4-178c11a9c7ab)

After changing Fx still equalizer is working on FX Booster it is not changing to the normal. In other music player it is working. 

![Screenshot_2024-03-30-17-04-26-543_com miui audioeffect](https://github.com/AkaneTan/Gramophone/assets/40023187/3a76179a-37e5-45ea-82f1-f00a2e62f8a9)

 - Device: [Redmi note 10 ]
 - OS: [Android 12]
 - App Version: 1.0.4.1

**Comment by nift4** [comment]
did you enable float audio output? note to self: i should add a warning that eq cannot work with float audio

**Comment by prajwalpatil2204** [comment]
> did you enable float audio output? note to self: i should add a warning that eq cannot work with float audio

I am  not using 32 bit float output.  This same issue is also with Accord.

**Comment by Szuwax** [comment]
Have the same issue(IDK how I miss that post):

Describe the bug
Equalizer is not working.

Equalizer in Gramophone app(AFAIK it is default android equalizer) is not working. You can turn it on but there is no difference in sound.

To be sure that it can be a poblem with Gramophone app I was tested the same function in another music player ( https://github.com/OxygenCobalt/Auxio )and there everything is working correct.

Smartphone (please complete the following information):

    Pixel 7 pro
    GrapheneOS 2024060500
    1.0.8.04a37e

**Comment by nift4** [comment]
why did you close it? is it working now?
