### ISSUE TITLE
[FR] Subfragment specific Shuffle button 

### ISSUE THREAD

**Issue by Maha-Rajan** [FoedusProgramme/Gramophone#149]
**Is your feature request related to a problem? Please describe.**
I prefer to use the album view and not the Songs view. The shuffle button is present only on the songs view.

**Describe the solution you'd like**
I would like to have the shuffle button on the album view too. Preferably the same place for visual consistency 

**Describe alternatives you've considered**
This is the primary reason I switched to other open source music players like Auxio

**Comment by nift4** [comment]
@Maha-Rajan I don't understand, how do you want to shuffle albums? Or do you want the same shuffle functionality as song tab in the album page?

**Comment by Maha-Rajan** [comment]
The same shuffle functionality as how it is treated in the song tab.

**Comment by nift4** [comment]
Added to three-button menu
