### ISSUE TITLE
[BUG] Wrong Icon direction in RTL layout

### ISSUE THREAD

**Issue by pxeemo** [FoedusProgramme/Gramophone#150]
**Describe the bug**
There is a visual bug related to the incorrect position of slider icons in RTL (Right-to-Left) languages.

**To Reproduce**
1. Change the language of the app or system to an RTL language, such as Arabic or Persian.
2. Open Gramophone’s settings.
3. Navigate to a slider with an icon setting item.
4. Observe that the icon is positioned on the left and overflows.

**Expected behavior**
The icon should be positioned on the right before the text starts.

**Screenshots**
![Screenshot_20240404-230939_Gramophone~3](https://github.com/AkaneTan/Gramophone/assets/67392584/9980f3c3-2139-4272-a7b6-8252c7ea43ab)

**Smartphone (please complete the following information):**
 - Device: POCO M3
 - OS: Android 14
 - App Version: 1.0.4.1.26cb03

**Additional context**

**Comment by lightsummer233** [comment]
Fixed in https://github.com/AkaneTan/Gramophone/commit/f5a33baa8dfbc5499d70335b4c5d01367f622f80
