### ISSUE TITLE
 [FR] Rearrange Titles in Queue Using Gestures

### ISSUE THREAD

**Issue by TechD123** [FoedusProgramme/Gramophone#154]
**Is your feature request related to a problem? Please describe.**
Rearranging the order of the queue is not possible in an easy manner. There is the possibility to use the "play next" feature for this, but it isn't nearly as efficient as using gestures.

**Describe the solution you'd like**
Quite often you want to change the order of the songs in the queue, which is not possible at the moment. One way to elegantly solve this would be by having a way to tap and drag a song to the desired position. For an example, take a look at Retro/Metro music player.

**Describe alternatives you've considered**
Gestures are likely to be the most intuitive solution.

Thanks for the great app!

**Comment by nift4** [comment]
@TechD123 Yep this is planned, thanks for your request.

**Comment by TechD123** [comment]
Awesome! Loving the clean design of the app by the way.

**Comment by nift4** [comment]
This has been added to the code and will be available next release
