### ISSUE TITLE
Able to choose displayed tabs

### ISSUE THREAD

**Issue by mxKeaton** [FoedusProgramme/Gramophone#158]
**Is your feature request related to a problem? Please describe.**
The tabs on the top, ranging from title to playlist, are overkill for regular use and also cumbersome if you regularly use features at the end of the list, like folders or playlists.

**Describe the solution you'd like**
I would like to be able to choose what tabs to display. So if I just want to see the titles and albums, I can hide all others. Identical or similiar to how Symphony (another music player) does it.

**Describe alternatives you've considered**
Either let me decide what tabs to display or allow me to hide tabs I don't want to interact with. Simple checkboxes.

**Comment by AkaneTan** [comment]
Duplicated issue #83
