### ISSUE TITLE
Fastlane: changelog is too long

### ISSUE THREAD

**Issue by IzzySoft** [FoedusProgramme/Gramophone#161]
I saw you've started using Fastlane changelogs, wonderful! Please note they are limited to 500 chars per file – your current one is almost 3 times as big and thus would be truncated exactly at position 500, which is mid-word. Please take care that future changelogs stay within the limit :wink:

Thanks!

**Comment by nift4** [comment]
Will do, thanks for the heads up :)

**Comment by IzzySoft** [comment]
Thanks! And there's always my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) for quick reference when needed :wink:
