### ISSUE TITLE
[BUG] Songs not shown until opened in another app

### ISSUE THREAD

**Issue by lukecdavidson** [FoedusProgramme/Gramophone#164]
**Describe the bug**
Songs aren't shown in the app until I open them in another app. I all songs in the Music folder, but Gramophone doesn't see any of them until I open them in another app like VLC. I have to do it for every single song in order for Gramophone to see them.

**To Reproduce**
1. Download a MP4 song to Music folder, where all other songs are saved.
2. Open Gramophone and refresh using the top right menu. Gramophone doesn't see the new song yet.
3. Open the Files app and navigate to the new MP4. Open with VLC. The song starts playing.
4. Repeat step 2. The song now shows in Gramophone.

**Expected behavior**
New songs in the Music folder to appear in Gramophone in refresh.

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6
 - OS: Android 14 Build 2024040900. Running GrapheneOS
 - App Version: version 1.0.5

org.akanework.gramophone
versionCode 7

targetSdk 34
minSdk 21

Installed: Apr 20, 2024; 3:19 PM

**Additional context**
Tried force stopping the app, same result. Reboot does fix it.

**Comment by nift4** [comment]
MP4 song? like .m4a?

**Comment by lukecdavidson** [comment]
Sorry, MP3. Yes, they are m4a.

**Comment by nift4** [comment]
I have no idea how you are downloading the songs, but if reboot and opening the file fixes it it's a pretty clear conclusion - MediaStore does not know about the file. I only managed to make that happen when using `adb push` on AOSP, though your modified Android version may also be to blame. As Gramophone never actually scans the file system itself, I can assure you the way you download your file must be the issue. Another possible workaround would be https://f-droid.org/packages/com.gmail.jerickson314.sdscanner/
