### ISSUE TITLE
Add long press on sleep timer

### ISSUE THREAD

**Issue by MostafaMohamed2002** [FoedusProgramme/Gramophone#165]

**Comment by MostafaMohamed2002** [comment]
I will try to do it cause i need it

**Comment by nift4** [comment]
wdym by long press?

**Comment by MostafaMohamed2002** [comment]
i mean when you set a timer , you can't know when will it stop or how much time left

**Comment by nift4** [comment]
that makes sense - i'll add it to the popup till the next release
