### ISSUE TITLE
[BUG] Song cover cannot be displayed on Android 10

### ISSUE THREAD

**Issue by Super12138** [FoedusProgramme/Gramophone#166]
**Describe the bug**
Song cover can't be displayed on Android 10 devices

**To Reproduce**
1. Open app
2. See error

**Expected behavior**
Display song covers correctly

**Screenshots**
Like this:
![Screenshot_20240423_222306.jpg](https://github.com/AkaneTan/Gramophone/assets/70494801/a0e6924a-82c5-4513-9b3e-2489e51901f2)

**Smartphone (please complete the following information):**
 - Device: HUAWEI P30
 - OS: HarmonyOS 4 (Android 10)
 - App Version: 1.0.5.f3ad1a (7)

**Additional context**

**Comment by AkaneTan** [comment]
@Super12138 Can you send that track's file here?

**Comment by Super12138** [comment]
Emm...
I've built the latest version, and it can be displayed normally again. But I haven't found the cause of the error yet.
