### ISSUE TITLE
Some music plays distortedly

### ISSUE THREAD

**Issue by senolfndk** [FoedusProgramme/Gramophone#167]
https://github.com/AkaneTan/Gramophone/assets/52818836/b149c63b-9e20-4fa6-a70b-7817703d35ea

**Comment by lolouthefox** [comment]
Can we even just get an explanation?

**Comment by senolfndk** [comment]
> Bir açıklama bile alabilir miyiz?
If you want, watch the video. Some of the music is playing distortedly.

**Comment by senolfndk** [comment]
> Bir açıklama bile alabilir miyiz?

If you want, watch the video. Some of the music is playing distortedly.

**Comment by lolouthefox** [comment]
> > Bir açıklama bile alabilir miyiz?
> 
> If you want, watch the video. Some of the music is playing distortedly.

Ok but what are the file type etc... what version of the app, etc...
Just make a full bug report 😂

**Comment by AkaneTan** [comment]
File a bug report properly or we won't accept it. And remember that you're not paying for this app.
