### ISSUE TITLE
some sounds are playing distortedly

### ISSUE THREAD

**Issue by senolfndk** [FoedusProgramme/Gramophone#168]
accord
file mp3
samsung galaxy a21s
Android 12
![Screenshot_20240425-124202_Accord](https://github.com/AkaneTan/Gramophone/assets/52818836/adbac961-1b35-4932-9743-7d05620dadff)

**Comment by AkaneTan** [comment]
1. This repository is for gramophone and you can find accord repository [here](https://github.com/AkaneFoundation/Accord).
2. When filing a report, please follow the standard [report format](https://github.com/AkaneTan/Gramophone/blob/beta/.github/ISSUE_TEMPLATE/bug_report.md)
3. Please use English for your screenshots, issue contents etc.
