### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by NimeshBhavsar** [FoedusProgramme/Gramophone#169]
Application Crashed during playing a locally stored song via Bluetooth Headphones while Charging the phone. 

This is the First time I saw this crash. Finding to reproduce the issue to get more detail

[ Screenshots Attached for error ]

 - Device: Realme 6 pro
 - OS: Android 11
 - App Version: 1.0.2.a13566

![Screenshot_2024-04-26-18-33-42-00_7b63ba6ba855e67dd5ee1b08e9300b77.jpg](https://github.com/AkaneTan/Gramophone/assets/70558093/d03f0a7e-119c-4f15-9f40-6be7ca4a7506)

**Comment by AkaneTan** [comment]
@NimeshBhavsar Have you tried the newest update?

**Comment by NimeshBhavsar** [comment]
> @NimeshBhavsar Have you tried the newest update?

No I am still on older version. I will update this until then keep this issue on hold.

Thankyou.

**Comment by AkaneTan** [comment]
@NimeshBhavsar I believe it's a solved bug in version 1.0.5 so I'll close this for now.
