### ISSUE TITLE
Fall back to recording year if release year isn't set

### ISSUE THREAD

**Issue by 766F6964** [FoedusProgramme/Gramophone#171]
**Describe the bug**
For some mp3 songs, they show up in Gramophone under the _Dates_ tab as _Unknown Year_, even tho the year is clearly set in the mp3 metadata. The screenshot below shows the mp3 metadata of the song, one can see 2018 is set:

![Screenshot from 2024-04-30 15-26-13](https://github.com/AkaneTan/Gramophone/assets/34845270/bdf3f77d-6c1d-47b3-8036-26bc7ba81bc8)
However, it shows up as "Unknown Year" in Gramophone:
![signal-2024-04-30-152734_002-obfuscated2](https://github.com/AkaneTan/Gramophone/assets/34845270/43829d38-de3b-437b-b1db-4ee0331b1bbd)

**To Reproduce**
1. Download this zip with an mp3 that showcases the issue: 
[Terrestria III- Wither.zip](https://github.com/AkaneTan/Gramophone/files/15164712/Terrestria.III-.Wither.zip)
2. Transfer the mp3 to the phone and open Gramophone.
3. Navigate to the "Dates" tab
4. Notice it shows up as "Unknown Year", instead of "2018", like set in the mp3's metadata.

**Expected behavior**
The song should show up in the _Dates_ tab under the correct year, that is set in the mp3 metadata.

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: GrapheneOS (Android 14) Buildno: 2024042100
 - App Version: 1.0.5.f3ad1a

**Additional Context:**
Other applications (such as GNOME music player) display the year perfectly fine, so I assume that this problem is specific to Gramophone.

**Comment by nift4** [comment]
Is it recording or release year? Gramophone only reads release year field.

**Comment by 766F6964** [comment]
> Is it recording or release year? Gramophone only reads release year field.

Yea, that one seems to be empty when I read the file tags with `id3v2`. Maybe it would make sense to use that field, if the release year field is empty?

**Comment by nift4** [comment]
Certainly a valid feature request, adding to backlog
