### ISSUE TITLE
README.md Building section confusion

### ISSUE THREAD

**Issue by DanrDoesCode** [FoedusProgramme/Gramophone#175]
I didn't find the issue template that matches the category i wanted, so i make an empty issue without the template, but its related to `Documentation`.

So in the `README.md` section `Building` ([Set up package type](https://github.com/AkaneTan/Gramophone?tab=readme-ov-file#set-up-package-type))

> Simply navigate to the root folder of the repository. Then you should create a file with the name 'package.properties'.
> 
> `$ touch package.properties`
> In it type:
> 
> `releaseType=SelfBuilt`

In my opinion, creating a new file and typing the things can be confusing to some users, i think it should be:

> Open your favorite text editor, type `releaseType=SelfBuilt`, and save it in the root folder of the repository as `package.properties`

or

> Simply navigate to the root folder of the repository. Then create a file with the name 'package.properties'.
> 
> `$ touch package.properties`
> Open it in your favorite text editor, and type:
> 
> `releaseType=SelfBuilt`
> 
> And save it

If there is anything wrong, please correct me 😄

**Comment by nift4** [comment]
Done, thanks
