### ISSUE TITLE
Changing the order of tab lists

### ISSUE THREAD

**Issue by k0nstruct** [FoedusProgramme/Gramophone#176]
**Is your feature request related to a problem? Please describe.**
Some of the listed tabs in the apps (like "Genres" and "Folders") are a bit superfluous to me, it sucks that I can't reorder them or disable them completely, since the Playlists tab is at the very end you have to scroll all the way there every time to get to it. 

**Describe the solution you'd like**
In the settings, add a menu with movable tick-boxes to chose which tabs are shown, and in what order.

**Describe alternatives you've considered**
Choose what tab to open by default at the start of the app instead of the first one that lists all the songs.

**Additional context**
I really like this project:) take ur time

**Comment by AkaneTan** [comment]
Duplicated issue #83
