### ISSUE TITLE
Multitasking interface, widget, shortcut

### ISSUE THREAD

**Issue by wj9559** [FoedusProgramme/Gramophone#177]
**Is your feature request related to a problem? Please describe.**
If you want to listen to music with this app, the multitasking interface will leave the card and you can't cross it out yet. 

**Describe the solution you'd like**
A widget or a shortcut (long press the icon).

**Comment by nift4** [comment]
Hey, what did you mean by "the multitasking interface will leave the card"?

**Comment by AkaneTan** [comment]
Closing this as there's no further explanation or activities
