### ISSUE TITLE
[BUG] Inconsistent Queue List

### ISSUE THREAD

**Issue by topazrn** [FoedusProgramme/Gramophone#182]
**Describe the bug**
Upon removing songs from queue, some songs are not removed.

**To Reproduce**
1. Play any song.
2. Open "Current Playlist"
3. Remove 3 songs after the current song.
4. Close "Current Playlist"
5. Open "Current Playlist"
6. Notice that only 2 songs are removed, the first and the last. The second song was not removed.

**Expected behavior**
Removed songs should be removed.

**Screenshots**

1.0.5: Problem did not exist

https://github.com/AkaneTan/Gramophone/assets/40129033/cbf906b8-5044-44de-b7e9-88257ef5d7ed

1.0.6: Problem exist

https://github.com/AkaneTan/Gramophone/assets/40129033/d743818e-a885-4c1b-af4d-31f1e0016899

As you can see, even though I've removed the second song (Bayonetta), it still persists.

**Smartphone (please complete the following information):**
 - Device: Poco F5
 - OS: Android 14
 - App Version: 1.0.6

**Additional context**
Tried other combination of songs to remove but I can't wrap my head around what changes. Feels like the queue got randomly reordered. Removing 3 songs after the current song is the most consistent case I can provide as it always leaves the second song to persist.

**Comment by nift4** [comment]
Can confirm, thanks
