### ISSUE TITLE
[BUG] F-Droid build not reproducible

### ISSUE THREAD

**Issue by linsui** [FoedusProgramme/Gramophone#184]
https://gitlab.com/fdroid/fdroiddata/-/jobs/6933557830

There are two problems.

1. the AboutLibraries plugin adds timestamp to the JSON file which can be removed. See https://f-droid.org/en/docs/Reproducible_Builds/#aboutlibraries-gradle-plugin
2. some images are different which seems to be caused by https://f-droid.org/en/docs/Reproducible_Builds/#pngs-generated-from-vector-drawables.

Could you please take a look? Thanks!

**Comment by nift4** [comment]
the agp docs say png generation only happens with minsdk<21 but we set 21, how can i know if that actually is the issue without another release?

**Comment by linsui** [comment]
You can upload the apk here. I'll check it locally. The png difference may be caused by https://f-droid.org/en/docs/Reproducible_Builds/#png-crushcrunch.

**Comment by nift4** [comment]
bafb808 - 
[Gramophone-1.0.6.bafb80-release.apk.zip](https://github.com/AkaneTan/Gramophone/files/15442410/Gramophone-1.0.6.bafb80-release.apk.zip)

Thanks for your efforts ;)

**Comment by linsui** [comment]
Looks like the above issues are fixed but there are some other issues. 
[org.akanework.gramophone_8.apk.html.zip](https://github.com/AkaneTan/Gramophone/files/15442479/org.akanework.gramophone_8.apk.html.zip)

**Comment by nift4** [comment]
the other issues seem to be caching of aboutlibraries and a local setup issue - thanks

**Comment by nift4** [comment]
https://github.com/AkaneTan/Gramophone/releases/tag/1.0.7 new release and I really hope it works now

**Comment by linsui** [comment]
The aboutLibraries json is different. Yours has more libs. I guess it's still a cache issue. Could please do a clean rebuild?

**Comment by nift4** [comment]
[Gramophone-1.0.7-release.apk.zip](https://github.com/user-attachments/files/15522738/Gramophone-1.0.7-release.apk.zip)
does this one work?

**Comment by linsui** [comment]
No, some libs have different version. Is it from https://github.com/AkaneTan/Gramophone/commit/be661ce08fde24e963aa569b61378f5d8f96905c instead?

**Comment by nift4** [comment]
[Gramophone-1.0.7-release.apk.zip](https://github.com/user-attachments/files/15522778/Gramophone-1.0.7-release.apk.zip)
does this work? I cleared every gradle cache I could find

**Comment by linsui** [comment]
It works, thanks!

**Comment by nift4** [comment]
Do I have to upload this into the release/create a new one for it to be propagated to F-Droid? be661ce08fde24e963aa569b61378f5d8f96905c would be a good opportunity anyway

**Comment by linsui** [comment]
Yes, please update the current release apk or create a new release.

**Comment by nift4** [comment]
Ok will do, thanks for your help

**Comment by nift4** [comment]
There we go: https://github.com/AkaneTan/Gramophone/releases/tag/1.0.8

**Comment by linsui** [comment]
Thanks!

**Comment by licaon-kter** [comment]
do reopen

ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/7800251608#L734

diff log: [gram13.log](https://github.com/user-attachments/files/16965984/gram13.log)

@nift4 looks like you tagged https://github.com/AkaneTan/Gramophone/releases/tag/1.0.11 to https://github.com/AkaneTan/Gramophone/commit/0fc89695d120cc257433d2af55a7e7db6d9ccbbc

but the APK was built from https://github.com/AkaneTan/Gramophone/commit/c57dbe ?

we understand you need to test commits, but please, when you're ready to release, after tagging, build the APK from the tagged commit, don't just upload some random APK you had around 

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/2c4d60e9092b1670d964f1730e5ef40d58534565

**Comment by linsui** [comment]
I would say it's easier to just disable the vcsInfo. :)

**Comment by nift4** [comment]
@licaon-kter sorry about that, I uploaded a new APK from the proper commit this time, let me know if there's any further issues

**Comment by licaon-kter** [comment]
@linsui as the log shows, it's not a vcsinfo issue as the app hardcodes the hash in its code/views

**Comment by licaon-kter** [comment]
@nift4 we're a bit better, now only .json differences remain: [gram13_2.log](https://github.com/user-attachments/files/16966511/gram13_2.log)


can you try to clean up gradle caches, and whatever cache you have locally, or maybe try to build from a clean clone of https://github.com/AkaneTan/Gramophone/commit/0fc89695d120cc257433d2af55a7e7db6d9ccbbc ?

**Comment by nift4** [comment]
@licaon-kter i cleared ~/.gradle/caches entirely and uploaded another APK, please let me know if it helped

**Comment by licaon-kter** [comment]
@nift4 that's better, thanks, fyi https://gitlab.com/fdroid/fdroiddata/-/commit/cfc250287e9e3c0aa3c14f4f587953ad608a59cb

**Comment by linsui** [comment]
Thanks!
