### ISSUE TITLE
Gramophone on OpenAPK

### ISSUE THREAD

**Issue by mobilenetworkltd** [FoedusProgramme/Gramophone#191]
Hey,

I'm running a open source repo for Android apps at https://www.openapk.net and I would like to have Gramophone listed in the repo. Please review the listing at https://github.com/AkaneTan/Gramophone

It is hooked to your GitHub repo so all the updates are automatically pushed to OpenAPK. Let me know if its ok !

If you are interested you can link to it and use our download banners ( https://www.openapk.net/images/openapk-badge.png )

**Comment by nift4** [comment]
Does it use fastlane for the description?

Anyway feel free to host it there
