### ISSUE TITLE
Show song length in album view

### ISSUE THREAD

**Issue by 766F6964** [FoedusProgramme/Gramophone#192]
**Feature request description**
It would be nice if the album view would also show the song length for each song in the album. Currently it only shows the song name and the artist name (which is redundant) but not the song length.

**Describe the solution you'd like**
Use the space on the right side where the three dot menu currently is to show the song length.

**Describe alternatives you've considered**
Maybe having a song length and the three dot menu both on the right side is not ideal. It might be sensible to completely hide the three dot menu and instead provide these options with a long press on the song.

**Additional context**
The space indicated with the red circles could be used to show the song length.

![IMG_20240602_063118](https://github.com/AkaneTan/Gramophone/assets/34845270/963d5ee3-10ed-490e-aea1-794bdbd22010)

**Comment by AkaneTan** [comment]
Closing this as it's not intended design
