### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Lucky390163** [FoedusProgramme/Gramophone#196]
Please add an
![Screenshot_20240602_223326_Gramophone](https://github.com/AkaneTan/Gramophone/assets/115852216/ee06f923-5a9b-41ab-a2d6-153140fe274b)
 option to disable visualisations.

It will improve my battery a lot just like Poweramp and AIMP

**Comment by nift4** [comment]
It's not a real visualization, just a random number generator. It's also not rendered while invisible, so it shouldn't have any effect on battery.
