### ISSUE TITLE
Move shuffle and repeat to current playlist

### ISSUE THREAD

**Issue by Jak2k** [FoedusProgramme/Gramophone#197]
**Is your feature request related to a problem? Please describe.**
Unnecessary clutter on in player

**Describe the solution you'd like**
Move "Shuffle" and "Repeat all" to "Current Playlist" and keep "Repeat song" in the player.

**Describe alternatives you've considered**

**Additional context**

**Comment by nift4** [comment]
Hi, thanks for your suggestion. However, shuffle and repeat are apparently the most used buttons for a majority of users and the reaction in our discussion group has been disagreement as well. Hence, we won't copy apple's weird button arrangement.
