### ISSUE TITLE
[FR] clicking on artist name show you artist

### ISSUE THREAD

**Issue by krzemyczek** [FoedusProgramme/Gramophone#198]
**Describe the solution you'd like**
If you play music it would be great option if you could go to artist if you click their name. (If more artist select which one). The same by clicking title should go to album or if no album to artist

**Describe alternatives you've considered**
Just finding one.

(BTW. Thank you for sharing nice app:) )

**Comment by AkaneTan** [comment]
Duplicated issue #218
