### ISSUE TITLE
[FR] Enhancements

### ISSUE THREAD

**Issue by ghost** [FoedusProgramme/Gramophone#2]
.

**Comment by unseenlarks** [comment]
a very nice player, thank you.

using this thread as it stands, for further enhancements/suggestions.

-ability to exclude specific folders (alarms, ringtones, etc.) from being scanned by the player. or to be able to hide them within the app itself.

-a choice to hide categories (genre, albums, artists, years, etc.) as desired.

-or, the ability to edit the menu, as currently everything there is a duplicate of what is on screen (search, shuffle, all categories, and so on).
