### ISSUE TITLE
Equalizer is not working [BUG]

### ISSUE THREAD

**Issue by Szuwax** [FoedusProgramme/Gramophone#205]
**Describe the bug**
Equalizer is not working.

Equalizer in Gramophone app(AFAIK it is default android equalizer) is not working. You can turn it on but there is no difference in sound.

To be sure that it can be a poblem with Gramophone app I was tested the same function in another music player (   https://github.com/OxygenCobalt/Auxio )and there everything is working correct.

**Smartphone (please complete the following information):**
 - Pixel 7 pro
 - GrapheneOS 2024060500
 - 1.0.8.04a37e

**Comment by Szuwax** [comment]
Duplicated

**Comment by Szuwax** [comment]
Duplicated

**Comment by nift4** [comment]
[Gramophone-1.0.13.7a31da-release.apk.zip](https://github.com/user-attachments/files/17283177/Gramophone-1.0.13.7a31da-release.apk.zip)
This apk should fix the bug
