### ISSUE TITLE
[BUG] Lyrics do not line up properly on line break

### ISSUE THREAD

**Issue by sebastien46** [FoedusProgramme/Gramophone#206]
**Describe the bug**

When a line break occurs, the lines below the first one do not line up properly and are slightly offset to the left of the screen

**To Reproduce**
1. Go to any song
2. Play it
3. Go to it's lyrics

**Expected behavior**

Lyrics line up properly

**Screenshots**

<img src="https://github.com/AkaneTan/Gramophone/assets/57289288/71d96e16-36ee-4b8d-bb10-525917cc446d" width=25% height=25%>

**Smartphone (please complete the following information):**
 - Device: Pixel 7
 - OS: Android 14
 - App Version: 1.0.8

**Comment by nift4** [comment]
Your lyrics have space bar after the timestamp. You can enable "trim lyrics" in behaviour settings if you want to remove it. This isn't enabled by default because some people apparently do it on purpose.
