### ISSUE TITLE
[Issues with playback speed and broken songs]

### ISSUE THREAD

**Issue by NotAl2** [FoedusProgramme/Gramophone#207]
**Bug Description**
Some songs didn't play as intended at some spots having increased playback speed and broken songs as well. I tested the same files with other players (auxio, namida, etc) it worked fine. All files are mp3 so i don't think there should be issues with compatibility. Really liked gramophone's simplicity so hopefully this bug is fixed.

**To Reproduce**
1. Go to 'Gramophone'
2. Click on 'Song of your choice'

**Expected behavior**
For songs to play correctly like they do otherwise.

**Screenshots**
None

**Smartphone (please complete the following information):**
 - Device: Redmi Note 10S
 - OS: MIUI 14.0.9.0
 - App Version: around 1.0.6

**Additional context**
Nothing else. 
Thank you.

**Comment by nift4** [comment]
@NotAl2 disable skip silence

**Comment by NotAl2** [comment]
> @NotAl2 disable skip silence

okay thanks

**Comment by nift4** [comment]
Closing as this is not a bug (skip silence is intended for podcasts - documenting this better is already tracked in backlog). If this happens without skip silence feel free to reopen.
