### ISSUE TITLE
Weblate project owner unreachable

### ISSUE THREAD

**Issue by orangesunny** [FoedusProgramme/Gramophone#212]
Hello community,

AkaneTan previously requested free Libre hosting plan for your translations, but their e-mail address is now unreachable.
Can anyone else take over, or should we remove the project? https://hosted.weblate.org/projects/gramophone/

orangesunny, _Hosted Weblate admin_

**Comment by AkaneTan** [comment]
Hi. I changed my email address and I already updated my email address to dev@akane.uk in my weblate profile. Is that ok?

**Comment by orangesunny** [comment]
Thanks for the change and quick reaction. All fixed, I wish you happy Weblating!
