### ISSUE TITLE
[BUG] Text not fitting in the card when browsing albums

### ISSUE THREAD

**Issue by kuroi-9** [FoedusProgramme/Gramophone#213]
**Describe the bug**
The artist name may not fit in the cards when browsing albums :
- In the albums menu 
- In the artist's albums menu.
It depends of the text size defined in the Android device settings.

**To Reproduce**
1. Go to Android device settings > Accessibility > Display size and text
2. Increase the Font size option until you notice fit problem in the app, on my device it happens pretty quickly (value >= 2)

**Expected behavior**
The card should expend depending the height of the text inside (album + artist), to avoid cutting it from the bottom. So far, it seems only the artist name in impacted.

**Screenshots**
![Screenshot_20240701-023536](https://github.com/AkaneTan/Gramophone/assets/174134134/7e328bad-a999-47a2-89c2-223fc60d0eb1)
![Screenshot_20240701-023618](https://github.com/AkaneTan/Gramophone/assets/174134134/44d02559-143d-4887-9efc-42f0f6229720)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6
 - OS: Android 14
 - App Version: 1.0.8.04a37e

**Additional context**
None.

**Comment by nift4** [comment]
Thanks for the report, this is a serious accessibility issue and I will try to get it fixed in one of the next updates

**Comment by kuroi-9** [comment]
The issue seems to be solved, just tested. Thanks a bunch! :100:
