### ISSUE TITLE
[FR] Minimalist/intuitive navigation to related content from player menu

### ISSUE THREAD

**Issue by Slug-Cat** [FoedusProgramme/Gramophone#218]
**Is your feature request related to a problem? Please describe.**
Other media players have a very intuitive way to navigate to the album or artist of the song currently being played, via tapping the album art or artist name respectively. Since this is a very convenient feature, for a frequently required user action, which does not affect the visual elements of the interface (no cluttering) I'd very much like for this player to have this navigation option. 

**Describe the solution you'd like**
Touch fields as described above and shown below.

**Additional context**
![IMG_20240705_134228](https://github.com/AkaneTan/Gramophone/assets/53411759/de7d371f-6b17-4859-9e67-06ff7ffadc9d)

**Comment by k0nstruct** [comment]
I second this. The UI is inconvenient to navigate between what you're playing and the related artist, albums, or playlist.

**Comment by AkaneTan** [comment]
Closing this since resolved in #233
