### ISSUE TITLE
[FR] ignore min seconds in filesystem tab

### ISSUE THREAD

**Issue by akrram09** [FoedusProgramme/Gramophone#230]
**Is your feature request related to a problem? Please describe.**
Yes

**Describe the solution you'd like**
When you go to the filesystem tap you can find sound less then 60s for example sound effects, ringtones... Since there is no option to open files on the file manager it would be a great idea 

**Alternative solutions**
Add the option to open files from the file manager

**Comment by nift4** [comment]
you can now open files from file manager so gonna close it
