### ISSUE TITLE
[FR] File association for music files. (Set as default app for audio files)

### ISSUE THREAD

**Issue by ghost** [FoedusProgramme/Gramophone#234]
**Is your feature request related to a problem? Please describe.**
It's useful to set this app as default for opening audio files. However, the app doesn't support this.

**Describe the solution you'd like**
It would be nice if I could open any music file with Gramophone, just like [Auxio](https://github.com/OxygenCobalt/Auxio) does.

**Describe alternatives you've considered**
[Auxio](https://github.com/OxygenCobalt/Auxio)

**Additional context**
...

- [x] I will follow the issue format and will add `[FR]` to the start of my issue title, and I acknowledge that if I don't follow the format, my issue might get closed without further explanation.

**Comment by nift4** [comment]
This has been added

**Comment by ghost** [comment]
Thanks, but wouldn't it be better to open it in the app itself, instead of playing the audio as a popup?

When I minimize the file manager, the audio stops playing. I'm sure that's not what most people want.

Thank you for your efforts BTW

**Comment by nift4** [comment]
Hi, that will be tracked in #279
