### ISSUE TITLE
[FR] Fading edges for scrolling text

### ISSUE THREAD

**Issue by ghost** [FoedusProgramme/Gramophone#237]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when text becomes too long (at this point, player starts to scroll it, and when it leaves the text box boundaries, it gets cut off).

**Describe the solution you'd like**
Add fading edges for scrolling text in app

**Additional context**
### How it looks now (w is cut off)
![photo_2024-08-12_03-11-06](https://github.com/user-attachments/assets/76ce0348-b845-4ea0-b671-1891ef407f28)
### Same thing in mini player
![photo_2024-08-12_03-13-12](https://github.com/user-attachments/assets/496d5f76-3dd1-491a-8815-724491088c9b)
### How it should look
![photo_2024-08-12_03-15-56](https://github.com/user-attachments/assets/09f65c95-3c94-4571-81d3-ca414ecf2e5b)

- [x] I will follow the issue format and will add `[FR]` to the start of my issue title, and I acknowledge that if I don't follow the format, my issue might get closed without further explanation.

**Comment by lightsummer233** [comment]
Added in 968d92e
https://github.com/AkaneTan/Gramophone/actions/runs/10345658748
