### ISSUE TITLE
add possibility to play .wav files

### ISSUE THREAD

**Issue by Pauler221** [FoedusProgramme/Gramophone#25]
Great improvement to the previous Symphonica version! I like the new project. The only thing I'm missing is the ability to play other file formats like .wav. 

It would be really convenient if you'd add the possibility to play .wav files.

**Comment by AkaneTan** [comment]
https://github.com/AkaneTan/Gramophone/commit/c28e7b2cff1815a5a68089382203b6a38ac4b9c4
Added ogg/wav format here for older android.
You can check this build to see if the wav formatted song is there
[Gramophone-1.0.1.c28e7b-release.apk.zip](https://github.com/AkaneTan/Gramophone/files/12793705/Gramophone-1.0.1.c28e7b-release.apk.zip)

**Comment by Pauler221** [comment]
Unfortunately the app isn't showing the song. Even after moving the song into a folder that shows up in the app the particular song won't show up in the app.

What's not working either is using a file manager and clicking on the song since Gramophone isn't shown in the possible apps that could open the file format. 

This file manager issue isn't isolated to the .wav format only. It won't work for any format even .mp3.

**Comment by nift4** [comment]
yes, starting from file manager is currently not implemented - for the song not showing up, can you perhaps upload the file and explain your exact device + OEM + android version?

**Comment by Pauler221** [comment]
.ogg is working fine when played through the app.

**Comment by Pauler221** [comment]
Pixel 6a running GrapheneOS (Android 13)

**Comment by nift4** [comment]
please don't spam @nekomekoraiyuu 

@Pauler221 how long is the wav file? is it perhaps below 60 seconds (the default value for minimum length, you can change it in settings)

**Comment by Pauler221** [comment]
@nift4 Yeah thanks I tried that as well. I changed it to 1 second. The file isn't shorter than 38 seconds.

**Comment by nift4** [comment]
can you send the exact wav file, so i can test on my android13 phone?

**Comment by Pauler221** [comment]
@nift4 Github doesn't support that file type. Where would you like me to share it?

**Comment by nift4** [comment]
you can pack it in an zip file, thats an old trick that always works XD

**Comment by Pauler221** [comment]
[air.zip](https://github.com/AkaneTan/Gramophone/files/12794146/air.zip)

Right my bad xd

**Comment by nift4** [comment]
Hi, MediaStore reports 0 duration so you need to set filter to 0 for it to appear, with 1 it does not show the file, I am not sure why this happens, can you please confirm if setting filter to 0 makes the file visible?

**Comment by nift4** [comment]
hello, quick update, i believe the file is corrupted or somehow in a format which is not supported by android, it can't be played back due to decoding failure, however if i import the file to audacity and export without change, file size is four times bigger, but there is some audio present and its 37 seconds long, the player does correctly display and play the file, therefore i believe wav support is working now.

**Comment by Pauler221** [comment]
@nift4 Yeah setting it to 0 makes the file show up but it's still unplayable. 
I can play the file with mpv (audio and video player) on android without any issues but it's possible that the file is in a weird format because an other open source music player (not mpv) has difficulties playing it as well.

**Comment by nift4** [comment]
because we rely on google ExoPlayer and as such system decoding libraries, if you really want support for this weird format, you need to report a bug to google ;) to me it makes more sense to just transcode it to something more compatible
