### ISSUE TITLE
[BUG] Just updated from 1.0.8 to 1.0.9 
& got kicked from the app

### ISSUE THREAD

**Issue by Ambientfish** [FoedusProgramme/Gramophone#253]
![Screenshot_20240903-023148.jpg](https://github.com/user-attachments/assets/e013fdd8-fc2e-4c38-90f6-dbb3d96a07ac)

idk why.

**Comment by nift4** [comment]
hi, can you try this apk and pls let me know if this still happens, thanks
[Gramophone-1.0.9.0aa6fc-release.zip](https://github.com/user-attachments/files/16880478/Gramophone-1.0.9.0aa6fc-release.zip)

**Comment by Ambientfish** [comment]
![Screenshot_20240907-042100.jpg](https://github.com/user-attachments/assets/5848ad2f-b1ca-4d51-9964-ab6cdb7c2a40)

Even this time.
It crashes again.

**Comment by nift4** [comment]
[Gramophone-1.0.9.ec7794-release.apk.zip](https://github.com/user-attachments/files/16947914/Gramophone-1.0.9.ec7794-release.apk.zip)
Please try this APK

**Comment by Ambientfish** [comment]
Thx bro ,the problem is solved rn :)
