### ISSUE TITLE
[FR] Edit metadata

### ISSUE THREAD

**Issue by ahstro** [FoedusProgramme/Gramophone#258]
It would be really neat if the metadata shown at the "Details"-screen was editable.
I.e. if a user goes to this menu option:
![image_2024_09_09_02_43_16](https://github.com/user-attachments/assets/9d999fc0-08d0-4652-8347-2a48d96aa5b5)

Any of these attributes should be editable:
![Screenshot_20240909-024026_Gramophone](https://github.com/user-attachments/assets/2055dce5-0a27-485c-868d-276b67bca6db)

<sub>also, thank you for a really cute and beautiful app! i really like it ~'*★♥</sub>

**Comment by nift4** [comment]
Hi, this feature is not planned, but thanks for the suggestion
