### ISSUE TITLE
[BUG] Metadata read incorrectly

### ISSUE THREAD

**Issue by ahstro** [FoedusProgramme/Gramophone#259]
**Describe the bug**
Metadata seems to be read incorrectly, or cached in some strange way.

**To Reproduce**
1. See song with wrong metadata
2. Alter metadata with tag editor, e.g. Kid3
3. Refresh
4. Keep seeing old/incorrect metadata
5. Clear cache
6. Step 4 again
7. Clear storage
8. Step 4 again
9. π-π

**Expected behavior**
After altering tags and refreshing, metadata and sorting should reflect the tags.

**Screenshots**
![Screenshot_20240909-190006_Gramophone](https://github.com/user-attachments/assets/84d46053-9419-48b7-8cb4-9edec67c4cca)
![Screenshot_20240909-190019_Kid3](https://github.com/user-attachments/assets/09ad4c40-7bc3-410b-b414-f773236ed3c0)

**Smartphone (please complete the following information):**
 - Device: OnePlus 7T Pro
 - OS: LineageOS 21
 - App Version: 1.0.9

**Comment by nift4** [comment]
try renaming the file (the cache isn't in Gramophone but in the system, rename is the easiest way to trigger it)

**Comment by ahstro** [comment]
OMG that worked!! Thank youu 😍
