### ISSUE TITLE
[BUG] App crashes on launch when Filipino is set as system language

### ISSUE THREAD

**Issue by searinminecraft** [FoedusProgramme/Gramophone#264]
**Describe the bug**

The app crashes on launch when the system language is set to Filipino. This may be an error in localization or a bug in the app

**To Reproduce**
1. Set system language to Filipino (if not an option, use AOSP/OneUI as they have that as an option)
2. Try to launch Gramophone, it should crash trying to load the songs

**Expected behavior**

The app launches correctly

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: samsung SM-J415GN
 - OS: LineageOS 19.1 - Android 12 (SQ3A.220705.004)
 - App Version: 1.0.11.0fc896

**Additional context**

I do not know if other languages are affected...

- [x] I will follow the issue format and will add `[BUG]` to the start of my issue title, and I acknowledge that if I don't follow the format, my issue might get closed without further explanation.

**Comment by searinminecraft** [comment]
Heres a recording of it happening:

https://github.com/user-attachments/assets/22fd1e08-02da-485e-a5b9-4ba6a527d63a

**Comment by nift4** [comment]
fixed, you should be able to download APK here soon, thanks for your report: https://github.com/AkaneTan/Gramophone/actions/runs/10939281255
