### ISSUE TITLE
[FR] Attempt to read generic 'application/octet-stream' album cover

### ISSUE THREAD

**Issue by cachiusa** [FoedusProgramme/Gramophone#266]
**Is your feature request related to a problem? Please describe.**

Music tag programs like VLC sometimes embed cover art in a format that Gramophone can't display
For example,
```
$ ffprobe Credits.mp3
ffprobe version 6.1.1-3ubuntu5 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 13 (Ubuntu 13.2.0-23ubuntu3)
  configuration: --prefix=/usr --extra-version=3ubuntu5 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --disable-omx --enable-gnutls --enable-libaom --enable-libass --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libharfbuzz --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-openal --enable-opencl --enable-opengl --disable-sndio --enable-libvpl --disable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-ladspa --enable-libbluray --enable-libjack --enable-libpulse --enable-librabbitmq --enable-librist --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libx264 --enable-libzmq --enable-libzvbi --enable-lv2 --enable-sdl2 --enable-libplacebo --enable-librav1e --enable-pocketsphinx --enable-librsvg --enable-libjxl --enable-shared
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
Unknown attached picture mimetype: application/octet-stream, skipping.
Input #0, mp3, from 'Credits.mp3':
  Metadata:
    title           : Credits
    artist          : Frums
    TRACKTOTAL      :
  Duration: 00:01:37.93, start: 0.025057, bitrate: 129 kb/s
  Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 128 kb/s
    Metadata:
      encoder         : LAME3.99r
    Side data:
      replaygain: track gain - 0.200000, track peak - unknown, album gain - unknown, album peak - unknown,
```
![6289498547636257072](https://github.com/user-attachments/assets/042fce88-1032-4890-adfe-a68d5dc8b82f)

However the preview player still displays the cover correctly(which I don't know why)
![6289498547636257073](https://github.com/user-attachments/assets/faefba9d-b61b-4dcb-a6dc-076e9b8914f1)

**Describe the solution you'd like**
Gramophone should attempt to decode album covers with mimetype 'application/octet-stream'

**Describe alternatives you've considered**
None.

**Additional context**
None.

- [x] I will follow the issue format and will add `[FR]` to the start of my issue title, and I acknowledge that if I don't follow the format, my issue might get closed without further explanation.

**Comment by nift4** [comment]
does this display in the song list or notification?

**Comment by cachiusa** [comment]
No

**Comment by cachiusa** [comment]
Should I send a sample file?

**Comment by nift4** [comment]
It's fine; we can't fix this anyway if it's not in the song list either.

Gramophone uses the Android system component called "MediaStore". It's job is to scan all media files on the storage devices and then provide a list of songs including their album covers. This allows to have loading times of milliseconds even for very large libraries. However, if there is a problem with exotic file combinations (like here), it's out of our control.

Meanwhile, the file preview player just directly opens the music file and reads the cover using Google's ExoPlayer.
