### ISSUE TITLE
[FR] Option to get synced or not synced lyrics from a provider

### ISSUE THREAD

**Issue by glaicodes** [FoedusProgramme/Gramophone#269]
**Is your feature request related to a problem? Please describe.**
I'm not a native speaker so looking at lyrics when listening to music helps me a lot for learning the language. Most of my downloaded songs don't come with lyrics so I would like

**Describe the solution you'd like**
I would like an option to search for lyrics

**Describe alternatives you've considered**
I've considered using Oto Music, which has this feature but it's not updated for more than a year and has it's problems

**Additional context**
These are the screenshots from oto music 
![Screenshot_20240926-233113](https://github.com/user-attachments/assets/b7fd8866-aee4-475f-812c-8e858f309987)
When you click the underlined text, it sends you to the lyrics editor screen (which is not necessary for this app imo)
![Screenshot_20240926-233128](https://github.com/user-attachments/assets/9ba3e1b1-b712-45f2-bd20-9a0d55c51e2f)
![Screenshot_20240926-233130](https://github.com/user-attachments/assets/b1434f2f-2a52-4658-b46d-8b16a1f14754)

- [ +] I will follow the issue format and will add `[FR]` to the start of my issue title, and I acknowledge that if I don't follow the format, my issue might get closed without further explanation.

**Comment by nift4** [comment]
Hi, this feature is not planned, but thanks for the suggestion. You could use https://github.com/Lambada10/SongSync instead
