### ISSUE TITLE
Support for Built-in Equalizer

### ISSUE THREAD

**Issue by ghost** [FoedusProgramme/Gramophone#270]
I have noticed that the music player app does not detect the built-in equalizer on my **Realme 11 Pro+**. 

![Screenshot_2024-09-27-21-20-42-78_7b63ba6ba855e67dd5ee1b08e9300b77](https://github.com/user-attachments/assets/cb656f48-7bda-4008-87df-b2fe5df6fbdd)

![Screenshot_2024-09-27-21-20-52-82_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/user-attachments/assets/296881da-bdfc-4d94-9e35-79982ea94a52)

**Comment by nift4** [comment]
Hi, this should be fixed in the next release. If it still happens in next release, please post a new bug report or ping me on this one. Thank you!
