### ISSUE TITLE
Scrolling text for long song titles

### ISSUE THREAD

**Issue by ghost** [FoedusProgramme/Gramophone#271]
When navigating through different menus in the music player app, I’ve noticed that long song titles are truncated with “...” at the end. This makes it difficult to identify songs accurately.

Proposed Solution: Implement a scrolling text feature for song titles. This would allow users to see the full title without truncation, improving usability and overall experience.

![Screenshot_2024-09-27-21-26-56-84_7b63ba6ba855e67dd5ee1b08e9300b77](https://github.com/user-attachments/assets/ea60447f-dd4f-4723-b351-7e84d34a7f5e)

**Comment by HaleyHalcyon** [comment]
Alternatively, titles could be shown in 2 lines.

This same problem happens in the “blacklist directory” settings menu.

**Comment by ghost** [comment]
2 lines could take more space imo and would not look good with other short song titles.

**Comment by AkaneTan** [comment]
Will cause **serious** performance issue as this was an option back in the testing stage so a big no.
