### ISSUE TITLE
Player slider style

### ISSUE THREAD

**Issue by ghost** [FoedusProgramme/Gramophone#272]
Introducing a new wavy playback bar for music playback would add a modern aesthetic matching the play/pause button. Users should have the option in settings to switch back to the traditional simple line bar if they prefer.
 
![Screenshot_2024-09-27-21-31-08-80_f4703f2d42345ac28c56f11a6100c500](https://github.com/user-attachments/assets/282988dc-a4fe-467e-be69-eefec43b7a1c)

**Comment by nift4** [comment]
already exists in settings

**Comment by ghost** [comment]
> already exists in settings

Sorry my bad. It was hard for me to identify it.
