### ISSUE TITLE
[FR] Allow choosing default tab at startup

### ISSUE THREAD

**Issue by thatAkiraFox** [FoedusProgramme/Gramophone#274]
**Is your feature request related to a problem? Please describe.**
I basically never use the "Songs" tab view, as I prefer to play songs by album.

**Describe the solution you'd like**
Would be useful to have the ability to set a tab as default when the app is opened.

**Describe alternatives you've considered**
Allowing to reorder tabs.
When the app opens it always starts on the leftmost tab, so when reordering we could use this mechanism to basically set a custom default tab (aka moving the preferred default tab at the start of the tab list).

**Additional context**
None.

- [x] I will follow the issue format and will add `[FR]` to the start of my issue title, and I acknowledge that if I don't follow the format, my issue might get closed without further explanation.

**Comment by nift4** [comment]
Added the alternative
