### ISSUE TITLE
[BUG] Mediastore reports misleading metadata info

### ISSUE THREAD

**Issue by Lucky390163** [FoedusProgramme/Gramophone#28]
It lacks feature to ingore mediastore library lack of this makes ablumart showing incorrectly

**Comment by nift4** [comment]
can you explain what you mean by "ignore mediastore library"?

**Comment by Lucky390163** [comment]
Mediastore library basically shows duplicate incorrect albumarts.

**Comment by AkaneTan** [comment]
@Lucky390163 The ideology of the Gramophone is to be a simplistic & vanilla player. Implementing our own metadata extraction method would violate this ideology. Maybe you should open an issue for mediastore in google's issue tracker and wait them to fix mediastore's problem.
