### ISSUE TITLE
[FR] Relocate Replay and Shuffle Buttons & Enhance Next/Previous Button Design

### ISSUE THREAD

**Issue by ghost** [FoedusProgramme/Gramophone#286]
**Proposed Change:**
Move the "Replay" and "Shuffle" buttons to be positioned directly next to the "Next" and "Previous" buttons to create a more seamless interaction when controlling playback.

**Material Design for Next/Previous Buttons:**
The Next and Previous buttons lack defined material design, resulting in a somewhat flat appearance.

![ResizedImage_2024-10-08_10-35-03_2457.jpg](https://github.com/user-attachments/assets/b8305b95-aa53-4cd3-808d-b45946e30219)

Concept i found for the buttons.
![Screenshot_2024-10-08-10-35-54-86_3aea4af51f236e4932235fdada7d1643.jpg](https://github.com/user-attachments/assets/55f61519-2958-4681-9d7c-6e270b428931)

**Comment by AkaneTan** [comment]
That’s oto music and we’re not doing that

**Comment by ghost** [comment]
Havent heard of oto music but ok sorry i guess.

**Comment by AkaneTan** [comment]
Just wanna say that material design is a very flexible thing and we’ll see some apparent UI changes in the upcoming 2.0 update. And thank you for your idea. (Tho I thought it’s from dribbble)

**Comment by ghost** [comment]
The FR is from a friend of mine that doesnt have a github account and he loves having material design on his apps. I dont know where he got that concept from could be dribble but it was just for idea purposes you dont have to copy it obv! Also updates on droidify are slow or what i cant test the new version 🥲
