### ISSUE TITLE
Mention in the description that you support "natural" sort order

### ISSUE THREAD

**Issue by JobLeonard** [FoedusProgramme/Gramophone#287]
This is actually a sneaky thank you note ;)

I just uninstalled a different (otherwise perfectly fine open source) offline music player because it didn't support this, and I realized that all of my CDs were ripped the "wrong" way. So hoping to save myself from an afternoon of filename renaming¹ I blindly installed this from F-Droid to see if it did support it, and it did! You should advertise it as a feature in the description!

Thanks again, the app seems lovely!

¹ even if I'd write a working regex + rename script for that, I'd still have to copy all files back to my android phone again

**Comment by nift4** [comment]
Done, thank you for the warm words :)
