### ISSUE TITLE
[FR] Make app_name translatable

### ISSUE THREAD

**Issue by BLumia** [FoedusProgramme/Gramophone#288]
**Is your feature request related to a problem? Please describe.**

Currently, the app name (Gramophone) is read-only and cannot be translated. For end-user who doesn't speak English or not good at English, the app name might be hard to recognize or remember. Also, the name (Gramophone) is not a trademark and is generic enough to be translated.

**Describe the solution you'd like**

Consider making it translatable, so the user can see the app name in a way that they can recognize and remember. (personally preferred solution)

**Describe alternatives you've considered**

Or, add an option to allow user set the app name? (would be not trivial to implement, though)

**Additional context**

N/A (let me know if you need any additional information)

- [x] I will follow the issue format and will add `[FR]` to the start of my issue title, and I acknowledge that if I don't follow the format, my issue might get closed without further explanation.

**Comment by AkaneTan** [comment]
https://github.com/AkaneTan/Gramophone/commit/c75f8195c69d5a1a71e6f5f2a7ed88e29d210693
Thanks for your suggestion! Marked as translatable in commit above.
