### ISSUE TITLE
[FR] Wallpaper-based Material You Theming Option

### ISSUE THREAD

**Issue by ghost** [FoedusProgramme/Gramophone#289]
Again a request from a friend on Discord. Currently, Gramophone's Material You theming relies on the album artwork to generate accent colors throughout the app (only on the "_now playing_" screen. While this is a fantastic feature, it would be beneficial to have an additional option in the settings to allow users to choose between the following theming options:

1. Album artwork colors (existing behavior)

2. Device wallpaper colors (following Material You theming based on the system's wallpaper)

**Comment by AkaneTan** [comment]
Hi. That switch already exists in settings. Simply turn off "Album color extraction" in appearance settings.

**Comment by ghost** [comment]
Told me he was confused cause he thought this was an appearance thing. Thanks again! Also do you guys have like a roadmap or something?

**Comment by nift4** [comment]
We do have one in our Telegram chat, but it's not fully up to date

**Comment by ghost** [comment]
Would it be possible to add it to the GitHub repository? (i dont use telegram unfortunately)

**Comment by nift4** [comment]
I'm too lazy to update it in two places lol. Are you curious if some feature is planned?

**Comment by ghost** [comment]
I totally get that! 😄 I just don't want to end up requesting features that are already planned so its not frustrating for you.

**Comment by nift4** [comment]
oh the issue tracker is plenty of a mess already, just request whatever, i'll close stuff when it doesn't make sense
