### ISSUE TITLE
Back gesture closes app

### ISSUE THREAD

**Issue by ghost** [FoedusProgramme/Gramophone#294]
The back gesture in the app closes it entirely instead of returning to the previous menu in certain sections, like the file system. This is frustrating, especially when navigating through long folders, as it requires scrolling back to the top. It would be more user-friendly if the back gesture allowed for easier navigation instead.

https://github.com/user-attachments/assets/fae2f9ff-9703-49bc-9fa0-e6454b499996

**Comment by ghost** [comment]
Am i a retard and this already exists in the settings?

**Comment by nift4** [comment]
The issue template for a feature request states:
[ ] I will follow the issue format and will add [FR] to the start of my issue title, and I acknowledge that if I don't follow the format, my issue might get closed without further explanation.
Akane did just that.

**Comment by ghost** [comment]
I didnt know this was a "feature" seemed more like a "bug" to me. Feature for me is like add a whole new thing into something or am i dumb

**Comment by nift4** [comment]
The issue template for a bug says:
[ ] I will follow the issue format and will add [BUG] to the start of my issue title, and I acknowledge that if I don't follow the format, my issue might get closed without further explanation.
Akane did just that.

A bug is if something that's intended to be working isn't working. The folder/filesystem UI never was intended to react to back button. If that makes sense is another question - one for an enhancement/feature request.

**Comment by ghost** [comment]
I see i am just clueless with these stuff mb
