### ISSUE TITLE
Playlist creation

### ISSUE THREAD

**Issue by ourslfs** [FoedusProgramme/Gramophone#30]
Would be nice to have an option to create playlist by adding folders instead of manually picking artists/albums (similar to how aimp handles playlist creation).

**Comment by nift4** [comment]
hi, playlists will be a list of songs, they won't be automatically modified by "all songs from artist" nor "all songs in this folder", reason being we store playlists in MediaStore.Audio.Playlists common component so they are stored inside your device and not inside the app.
