### ISSUE TITLE
Launcher Widget

### ISSUE THREAD

**Issue by Shizukuku** [FoedusProgramme/Gramophone#302]
First of all, thank you guys, I really like this music player! Is it possible to add a launcher widget in the future, like the style in the picture?

![IMG_20241021_130742.jpg](https://github.com/user-attachments/assets/17ab20b7-6546-48d5-96ad-1cc3c203d711)

**Comment by nift4** [comment]
Hi, this feature is being tracked in #242   hence closing as duplicate
