### ISSUE TITLE
Respect folder structure

### ISSUE THREAD

**Issue by surferjoeit** [FoedusProgramme/Gramophone#305]
It would be nice that folder view respect folder structure so that subfolder are properly nested. This in order to avoid having a lot of folders named 1, 2, 3, 4..... or CD1, CD2, etc... for albums with multiple discs.
Many Thanks

**Comment by nift4** [comment]
Use filesystem view for that

**Comment by surferjoeit** [comment]
Ok thanks. I can't see the difference between the two views. Anyway: any possibility to correctly sort tracks. Tracks are sorted alphabetically, and then in the wrong order as they're not sorted by track number or filename, but by song name.
Thanks!

**Comment by nift4** [comment]
Ah that's what you mean, it's tracked in #282

**Comment by surferjoeit** [comment]
The same issue occurs in folder view. Track sorting is only alphabetical. Folder view, as well as filesystem view is almost unusable without the possibility to modify sorting criteria.
