### ISSUE TITLE
[FR] Show play all/shuffle all buttons in every tab

### ISSUE THREAD

**Issue by lucaxvi** [FoedusProgramme/Gramophone#313]
The play all and shuffle all buttons are displayed only in the "Songs" tab.

https://github.com/AkaneTan/Gramophone/blob/4d4d711ccd9ff2d1262ff70fe621052dd8a0db7c/app/src/main/kotlin/org/akanework/gramophone/ui/adapters/BaseDecorAdapter.kt#L62-L65
https://github.com/AkaneTan/Gramophone/blob/4d4d711ccd9ff2d1262ff70fe621052dd8a0db7c/app/src/main/kotlin/org/akanework/gramophone/ui/adapters/BaseDecorAdapter.kt#L174-L186

I was wondering if there were downsides to showing these buttons in other tabs as well.

**Comment by nift4** [comment]
Semantically, the plan was to allow play all / shuffle of albums, so that each album is in correct song order but you get a random album. Similar stuff with other tabs if we're at it already.

**Comment by lucaxvi** [comment]
Sorry for making a duplicate of #149 and #200, I completely forgot to look. In the latter it was said that it's "not included in intended design" so does that mean a PR would not be welcome?

**Comment by nift4** [comment]
I'm surprised Akane closed #200 but kept #149 open, alas, reopened 149.

Just adding the shuffle and play button to the decor bar but always playing all songs is not something I'd plan to merge. Something like shuffle or play all in the three dot menu in addition to current place would be something I am open for.
