### ISSUE TITLE
[BUG] Highlighting issues in lyrics widget while using lyrics with translation entries

### ISSUE THREAD

**Issue by Lambada10** [FoedusProgramme/Gramophone#318]
**Describe the bug**
When using line-synced lyrics with translation, only the translation is highlighted while song is playing. When the song is paused, current line, current line translation and previous line translation are highlighted

**To Reproduce**
1. Have a song with translated lyrics
2. Create widget and play song
3. Only translated lines are being highlighted
4. Pause song
5. Click on lyrics line
6. Current line, current line translation and previous line translation are highlighted 

**Expected behavior**
Current line with its translation being highlighted

**Smartphone (please complete the following information):**
 - Device: Poco F5
 - OS: Paranoid Android 14
 - App Version: 1.0.15.697832

- [x] I will open one issue per bug, follow the issue format and will add `[BUG]` to the start of my issue title, and I acknowledge that if I don't follow the format, my issue might get closed without further explanation.

**Comment by nift4** [comment]
note to self: need to ignore translation in statusbarlyric?
