### ISSUE TITLE
[Question] Is Accord deprecated？

### ISSUE THREAD

**Issue by abcdesteve** [FoedusProgramme/Gramophone#320]
I know it isn't polite to mention another repo here, but [accord](https://github.com/FoedusProgramme/AccordLegacy) hasn't updated for quite long and the repo actually moved to another organization. Since issue function hadn't been enabled in that repo, I writing this issue to ask for details.

I really love the UI in Accord, and I know you are also the author of that project. If that project hasn't been deprecated, would you pls update it to follow Gramophone?

Or if it has been deprecated, would you consider adding another set of UI in Gramophone with a switch in settings? It will be nice to see such a great app continue to updated. It is the best UI I have ever seen, especially in its lyrics page.

**Comment by nift4** [comment]
Akane has announced that users can except Accord 2.0 some time around Christmas, you can join our chat to stay updated: https://t.me/FoedusDiscussion
