### ISSUE TITLE
About Collapsing tool bar 

### ISSUE THREAD

**Issue by MostafaMohamed2002** [FoedusProgramme/Gramophone#324]
How to achieve this with jetpack compose or even xml ?https://github.com/user-attachments/assets/e2d62006-c81a-4283-a649-cf37f0027a9b

**Comment by MostafaMohamed2002** [comment]
@nift4

**Comment by AkaneTan** [comment]
I thought gramophone is an open sourced app :)

**Comment by MostafaMohamed2002** [comment]
> I thought gramophone is an open sourced app :)

I searched the repository but couldn't find what I was looking for. Could you help me by sharing the names of the related files?

**Comment by AkaneTan** [comment]
https://github.com/AkaneTan/Gramophone/blob/a65b93d25ab69742c1943ad260482e12d00a001e/app/src/main/res/layout/fragment_general_sub.xml#L13
