### ISSUE TITLE
[BUG] save unset time index instead of EndedWorkaroundPlayer if STATE_ENDED

### ISSUE THREAD

**Issue by nift4** [FoedusProgramme/Gramophone#343]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - App Version: [e.g. 22]

**Additional context**

- [ ] I will open one issue per bug, follow the issue format and will add `[BUG]` to the start of my issue title, and I acknowledge that if I don't follow the format, my issue might get closed without further explanation.

**Comment by nift4** [comment]
@nift4 Changing the wrap-around to happen at save time would mean the timestamp shown in mini player / notification would be zero instead of EOF. does it matter?

**Comment by MACCEHTEPPOP** [comment]
@nift4 sssisksk

**Comment by nift4** [comment]
nevermind I prefer the hack over changed UX
