### ISSUE TITLE
[FR] Show m4a type songs

### ISSUE THREAD

**Issue by imshinyu** [FoedusProgramme/Gramophone#349]
i can't see my m4a type files

**Describe the solution you'd like**
show m4a type files
- [ ] I will open one issue per request, follow the issue format and will add `[FR]` to the start of my issue title, and I acknowledge that if I don't follow the format, my issue might get closed without further explanation.

**Comment by nift4** [comment]
Gramophone already supports the m4a container within the limits imposed by the Android system. There is a multitude of possible reasons why your files are not displayed, such as:
- Not using latest version 1.0.15
- Files are in a folder that is excluded from MediaStore using .nomedia file
- Files are in a folder that is excluded in Gramophone Behaviour settings
- Files are shorter than the configured minimum length setting, which is 60 seconds by default
- Very old Android version
- Corrupted file
- Files were recently downloaded into internal storage using adb/Termux and Android's MediaStore did not notice it so far
