### ISSUE TITLE
[FR] Support for external LRC file.

### ISSUE THREAD

**Issue by KoshikKumar17** [FoedusProgramme/Gramophone#358]
Please add support to show lyrics using external LRC file.
Else everything is nice.

A sample screenshot is from **Mi Music Player**
![Screenshot_2024-12-19-21-59-03-243_com miui player](https://github.com/user-attachments/assets/d3f255a9-fc61-496a-82fa-33e33a76d504)

**Comment by nift4** [comment]
what makes you think we don't?

**Comment by KoshikKumar17** [comment]
> what makes you think we don't?

It would be better, (at least for me). If you don't want then close this issue.

**Comment by nift4** [comment]
Verdion 1.0.15 supports external LRC files, have you tried it?

**Comment by KoshikKumar17** [comment]
There isn't any option to add external LRC file in the app.

**Comment by nift4** [comment]
We do expect the user to bring his own LRC file. You can use https://github.com/Lambada10/SongSync to download LRC files

**Comment by KoshikKumar17** [comment]
That's a nice combo. Thanks.
