### ISSUE TITLE
[BUG] Wrong translation license

### ISSUE THREAD

**Issue by comradekingu** [FoedusProgramme/Gramophone#36]
The translation files are licensed AGPLv3+, when the source code files are licensed GPLv3+

**Describe the bug**

The license of the translation files should be changed to GPLv3+

**To Reproduce**

Distribute app as GPLv3+, when files are AGPLv3+.
I think there is some in-built compatibility that allows this, but seems to be in error.

**Expected behavior**

https://hosted.weblate.org/projects/gramophone/#information
should match
https://github.com/AkaneTan/Gramophone/blob/beta/LICENSE

**Screenshots**

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser N/A
 - Version N/A

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**

Can be fixed in https://hosted.weblate.org/settings/gramophone/strings-xml/

**Comment by AkaneTan** [comment]
Oops, thanks for pointing out! Already fixed!
