### ISSUE TITLE
[BUG] System buttons with no backgrounds can be very hard to read in some situations

### ISSUE THREAD

**Issue by Porkepix** [FoedusProgramme/Gramophone#38]
**Describe the bug**
System buttons with no backgrounds can be very hard to read in some situations

**To Reproduce**
Just run Gramophone in on an Android presenting the buttons visible in the screenshot below

**Expected behavior**
It should be easier to read those buttons

**Screenshots**

<details>
<summary>
Screenshot
</summary>

![Screenshot_20231106-174843](https://github.com/AkaneTan/Gramophone/assets/709500/f25504a1-b291-4748-85cc-490cfa0acfee)
![Screenshot_20231106-173137](https://github.com/AkaneTan/Gramophone/assets/709500/532fea56-7248-48a0-b1e1-5fdb91919269)

</details>

**Smartphone (please complete the following information):**
 - Device: Xperia XZ
 - OS: Android Oreo (8.0)
 - Version 1.0.1

**Additional context**
This might be somewhat related to issues I reported where the buttons where white on a white background. I can add references to those issues if you think it'd be of any help.

**Comment by AkaneTan** [comment]
Already fixed in newest source code.
