### ISSUE TITLE
[BUG] When compared to README screenshots, tabs underlining seems like the upper part of something with no lower part

### ISSUE THREAD

**Issue by Porkepix** [FoedusProgramme/Gramophone#39]
**Describe the bug**
When compared to README screenshots, tabs underlining seems like the upper part of something with no lower part, see the screenshot below (purple underlining have rounded corner on the upper side but a straight cut on the lower side under "Songs").

**Expected behavior**
This looked more natural the way it looked on the README's screenshots, but slight redesigns might have happened since

**Screenshots**

<details>
<summary>
Screenshot
</summary>

![Screenshot_20231106-174843](https://github.com/AkaneTan/Gramophone/assets/709500/8dfd024c-882a-4516-9160-a73f987b2f98)

</details>

**Smartphone (please complete the following information):**
 - Device: Xperia XZ
 - OS: Android Oreo (8.0)
 - Version 1.0.1

**Comment by AkaneTan** [comment]
Ah thanks for reminding me to replace the screenshots! It's outdated a long time ago.

**Comment by Porkepix** [comment]
> Ah thanks for reminding me to replace the screenshots! It's outdated a long time ago.

So I guess it's intended that way? Because it looks like the underlining was sliced into two parts and only the upper one was kept, looks strange that way imho.

**Comment by AkaneTan** [comment]
That's intended by google 🤷, you can check that here:
https://m3.material.io/components/tabs/overview

**Comment by Porkepix** [comment]
Okay, thanks for pointing out. To each his own I guess…

**Comment by AkaneTan** [comment]
@Porkepix

**Comment by AkaneTan** [comment]
![Screenshot_20231112-083116_Gramophone.png](https://github.com/AkaneTan/Gramophone/assets/69606737/b099c484-a863-4d79-aec2-e0c0c83586b0)

We used a more "modern" approach for material design in current versions. So ig it's really the time to update the screenshots.
