### ISSUE TITLE
Request: armv7 build for test

### ISSUE THREAD

**Issue by PixelCode5** [FoedusProgramme/Gramophone#4]
Looking forward for armv7 build. I hope to provide some feedback on my older hardware.

**Comment by AkaneTan** [comment]
@PixelCode5 I don't think it's an architectural problem since there's no native libs in Gramophone. What's your android version?

**Comment by PixelCode5** [comment]
It's Lineage OS based on Android 11. I was trying to install if from Droid-ify which was missing option for amrv7 then tried obtainium which also failed. So I tried manually using SAI which is giving error "_There was problem parsing the package._"

**Comment by AkaneTan** [comment]
> It's Lineage OS based on Android 11. I was trying to install if from Droid-ify which was missing option for amrv7 then tried obtainium which also failed. So I tried manually using SAI which is giving error "_There was problem parsing the package._"

[app-debug.zip](https://github.com/AkaneTan/Gramophone/files/12567838/app-debug.zip)
I have lowered minSdk version to 21. Try this build and see if it crashes, please send logs if it does.

**Comment by PixelCode5** [comment]
Thank you, this one is working. I will provide feedback if I encounter any issues during my usage.

**Comment by AkaneTan** [comment]
@PixelCode5 👍🏻
