### ISSUE TITLE
you can't exclude the folders you need

### ISSUE THREAD

**Issue by subsubsubsubsubsub** [FoedusProgramme/Gramophone#40]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AkaneTan** [comment]
@subsubsubsubsubsub Create a folder name ".nomedia" under the folder you want to exclude. It's android mediastore's feature. Not going to include that in the future.

**Comment by subsubsubsubsubsub** [comment]
the folder is the phone records. if you add nomedai it still creates after a phone call

**Comment by AkaneTan** [comment]
@subsubsubsubsubsub I mean add a file named ".nomedia" under that folder. It won't go away whatsoever.

**Comment by subsubsubsubsubsub** [comment]
I did, and now I can't listen to the recording of the call.

**Comment by AkaneTan** [comment]
@subsubsubsubsubsub From where???

**Comment by subsubsubsubsubsub** [comment]
talk phone app
