### ISSUE TITLE
[FR] Prefered Disaply Style in Album Tab is not saved.

### ISSUE THREAD

**Issue by Ravi-Kishor** [FoedusProgramme/Gramophone#42]
**Describe the bug**

**To Reproduce**
1. Go to 'Alubum Tab'
2. Change Default view
3. Restrat the app
4. Bug:- the view reset to default one, (large Album art view)

**Desktop (please complete the following information):**
 - OS: Andoid 13
  - Version : Gramophone-1.0.2.00fe62-release

**Smartphone (please complete the following information):**
 - Device: Moto G54
 - OS: Andoid 13 Spet Patch

**Additional Feature Requests "Take ur Time"**
1. A good Home Screen Widget.
2. Option to set Default tab while opening app (Def one is songs, want to change it to Albums)
3. Add option to clear Playing Queue.
4. Tag Editor 

**Lastly, Thanks for such a beautiful Offline Music Player, Hope to see fixes and improments in future.**

**Comment by AkaneTan** [comment]
Ah, thanks for reaching out!
Saving sort order is not a feature present in current source code. But we'll add it once we're able to.
