### ISSUE TITLE
Lyrics support in .opus and .m4a files

### ISSUE THREAD

**Issue by HyroGoth** [FoedusProgramme/Gramophone#44]
**Is your feature request related to a problem? Please describe.**
Lyrics are not supported in opus files and not found in m4a 

**Describe the solution you'd like**
Added the support for opus and fix for m4a

**Describe alternatives you've considered**
Support for external lrc (Idk if its already implemented or it will be added in the next update, but I know the app already have)

**Comment by AkaneTan** [comment]
Already supports external lrc in current source code. Please wait till I update it in my channel at t.me/AkaneDevRel.
