### ISSUE TITLE
[FR] Editable Lyrics and Auto-fetch from Online

### ISSUE THREAD

**Issue by s-sarathb** [FoedusProgramme/Gramophone#46]
Dear Gramophone Development Team,

I hope this message finds you well. I am an avid user of the Gramophone app, and I must say that I thoroughly enjoy its sleek UI and seamless music playback experience. However, I have identified a couple of features that, in my opinion, could enhance the user experience even further.

Firstly, the ability to edit lyrics directly within the app would be a fantastic addition. Many users, including myself, often come across situations where we'd like to customize or correct lyrics for a more personalized experience. Incorporating an editable lyrics feature would undoubtedly cater to this need.

Secondly, an auto-fetch lyrics option from online sources would be immensely beneficial. This feature could save users time and effort by automatically retrieving accurate and up-to-date lyrics for the songs they're listening to. This could be particularly handy when exploring new music or rediscovering old favorites.

I understand that implementing new features requires time and resources, but I believe these additions would significantly elevate the Gramophone app's functionality and appeal to a broader audience.

Thank you for your dedication to providing an exceptional music listening experience. I look forward to potential updates and improvements.

**Comment by nift4** [comment]
Hi, to avoid bloating the app, we have no plans to do this. There are many great tag editing apps that fulfill this exact usecase better than we could, like MusicBrainz Picard or Kyant's tag editor.
