### ISSUE TITLE
[BUG] Whenever I click on Equalizer it shows "Equalizer not found"

### ISSUE THREAD

**Issue by ultimatebigchill7** [FoedusProgramme/Gramophone#48]
![ResizedImage_2023-12-01_21-43-03_0](https://github.com/AkaneTan/Gramophone/assets/149289922/a4151d16-a812-43d2-9ba2-2244d26bdbef)

**Comment by rickdtc** [comment]
@saibhargavtanneeru Do you have a system equalizer?

**Comment by AkaneTan** [comment]
@saibhargavtanneeru Gramophone doesn't have a inbuilt equalizer yet, so we depend on system's eq. If your system doesn't have it then it'll show "Equalizer not found". Maybe consider using external equalizers?

**Comment by ultimatebigchill7** [comment]
Hi,I have system equalizer.

**Comment by nift4** [comment]
which device / rom / os / android ver

**Comment by ultimatebigchill7** [comment]
Realme 8 4G
Model - RMX3085
Realme UI 4.0, Android 13

My internal equalizer works fine and it works while using Gramophone. It's just not opening my internal equalizer when I click on equalizer.

**Comment by AkaneTan** [comment]
Then it's a system bug. Please report to your system developers.

**Comment by ultimatebigchill7** [comment]
> Then it's a system bug. Please report to your system developers.

Sure👍, Thank You
