### ISSUE TITLE
[BUG] certain songs won't play on gramophone but will on other music players

### ISSUE THREAD

**Issue by airyandre** [FoedusProgramme/Gramophone#49]
for some reason, some songs won't even play even after refreshing so many times. i tried deleting the file and redowloading it a few times, even downloading it in different formats such as mp3 and flac but the result was the same. all my other songs have the same bitrate and file type

i decided to try to play the same file on oto music and it works flawlessly so i'm clueless about what it could be

no matter how many times i try, even force closing the app or deleting data or uninstall gramophone as a whole the result is the same

i downloaded all the songs i have using spowlo on default settings 
![Screenshot_20231202-142054](https://github.com/AkaneTan/Gramophone/assets/152658363/87c80da0-b5b7-4c4c-9acb-bad702d226da)
![Screenshot_20231202-142023](https://github.com/AkaneTan/Gramophone/assets/152658363/361485af-8b86-43e5-b68d-c4bed8ead124)

**Comment by nift4** [comment]
can you create bug report in developer settings and email it to me nift4@protonmail.com

**Comment by airyandre** [comment]
i just sent it, please check

**Comment by nift4** [comment]
@airyandre got it, will check

**Comment by nift4** [comment]
[Gramophone-1.0.2.bd8ec5-release.apk.zip](https://github.com/AkaneTan/Gramophone/files/13538499/Gramophone-1.0.2.bd8ec5-release.apk.zip)
 pls test

**Comment by AkaneTan** [comment]
Marking this as solved. This issue was resolved in https://github.com/AkaneTan/Gramophone/commit/bd8ec503e4256c1af9511961afdb901c97e9de2b

**Comment by airyandre** [comment]
@AkaneTan @nift4 it works perfectly now, thanks a lot for your time!
