### ISSUE TITLE
[BUG] UI Elements Overlapping for Small UI dp 640x360

### ISSUE THREAD

**Issue by PixelCode5** [FoedusProgramme/Gramophone#5]
I have small dp screen of width 360, as you can see in pic the song title and buttons are overlapping one another. Can you make it compatible for lower dp screen?
![Screenshot_Gramophone](https://github.com/AkaneTan/Gramophone/assets/111636162/5e8f5152-d9e0-4896-9504-586a8239d32f)

**Comment by AkaneTan** [comment]
Should be fixed rn since we've introduced constraintlayout. Closing this issue.
