### ISSUE TITLE
[BUG] "music format not supported!" text appears when trying to see lyrics

### ISSUE THREAD

**Issue by airyandre** [FoedusProgramme/Gramophone#50]
**Describe the bug**
after installing the version 1.0.2.bd8ec5 audio playback works great but there's a new issue now. whenever i try to read the lyrics of any song, the message described in the title will appear regardless of the song and audio format and quality.
**To Reproduce**
1. open gramophone
2. select any song
3. tap on the lyrics button
4. error shows up

**Expected behavior**
lyrics showing up normally and no error message should appear whatsoever

**Screenshots**
![Screenshot_20231203-083415](https://github.com/AkaneTan/Gramophone/assets/152658363/228e9a17-def8-4ed8-9e54-6eaafa9e4670)

**Smartphone (please complete the following information):**
 - Device: pixel 6
 - OS: android 14

**Comment by nift4** [comment]
1. what formats do your songs have (ogg container parsing is not supported ATM)?
2. i am rewriting lyrics parsing so if you need ogg, please tell me and I will add it
3. the app supports external .lrc file for unsupported formats in the meantime

**Comment by AkaneTan** [comment]
@nift4 No i fixed it in https://github.com/AkaneTan/Gramophone/commit/d74973ab0f4d2efb24825c0314d213a8a188baaf

**Comment by airyandre** [comment]
@nift4
1. i've been testing with flac and mp3 files
2. personally I don't need it but thank you
3. lyrics were working as expected before updating, all my songs have the lyrics embedded to their respective files

**Comment by nift4** [comment]
[Gramophone-1.0.2.312f69-release.apk.zip](https://github.com/AkaneTan/Gramophone/files/13539640/Gramophone-1.0.2.312f69-release.apk.zip)
