### ISSUE TITLE
[BUG] Crashes Upon Opening the App for the first time

### ISSUE THREAD

**Issue by KjStyles105** [FoedusProgramme/Gramophone#51]
**Describe the bug**
something about the permissions being denied "WRITE_EXTERNAL_STORAGE"

**To Reproduce**
1. Click on 'Gramophone'
2. See error

**Expected behavior**
when opening it for the first time it will crash saying about permission denied

**Screenshots**
![Screenshot_2023-12-03-23-34-55-72](https://github.com/AkaneTan/Gramophone/assets/102032560/86c2fe41-be98-401a-9ae1-af19e1b3c8c4)

**Smartphone (please complete the following information):**
 - Device: [e.g. OPPO A37S]
 - OS: [e.g. Android 5.1.1]
 - Browser [e.g. chrome]
 - Version [e.g. 1.0.2.88d94e]

**Comment by nift4** [comment]
https://github.com/AkaneTan/Gramophone/files/13538499/Gramophone-1.0.2.bd8ec5-release.apk.zip
fixed in this beta version, we will release it soon
