### ISSUE TITLE
[BUG] Crashes Upon Clicking a Song

### ISSUE THREAD

**Issue by KjStyles105** [FoedusProgramme/Gramophone#52]
**Describe the bug**
An error saying "No Virtual Method"

**To Reproduce**
1. Go to 'Gramophone'
2. Click on 'Any Song'

**Expected behavior**
crashes when clicking a song

**Screenshots**
![Screenshot_2023-12-03-23-58-17-43](https://github.com/AkaneTan/Gramophone/assets/102032560/6e630c6a-d5ea-4777-a58d-c9e986b9f4d9)

**Smartphone (please complete the following information):**
 - Device: [e.g. OPPO A37S]
 - OS: [e.g. android 5.1.1]
 - Browser [e.g. chrome]
 - Version [e.g. 1.0.2.bd8ec5]

**Comment by nift4** [comment]
seems like jaudiotagger doesn't support android 5, I will replace it with custom parsing

**Comment by AkaneTan** [comment]
Should be fixed with 19d4fa6041d6cd0a4c1bc3058e4c557263e4e284 and 6544430aeafdc975f76aa775c96285223aa38cb3, however, these commits still have problems and can't be used for production environment.
