### ISSUE TITLE
[BUG] There's a delay to show the songs, and it shows there are 0 songs for a couple of seconds

### ISSUE THREAD

**Issue by Porkepix** [FoedusProgramme/Gramophone#55]
**Describe the bug**
There's a delay to show the songs and it shows there's 0 songs for a couple of seconds on every start. Bug was experienced on the release from https://github.com/AkaneTan/Gramophone/issues/37#issuecomment-1837493118 and is a regression: 1.0.1 was showing everything instantly.

**To Reproduce**
Just launch the application

**Expected behavior**
This should be an instant show like it was on previous release.

**Smartphone (please complete the following information):**
 - Device: Xperia XZ
 - OS: Android Oreo 8.0
 - Release from https://github.com/AkaneTan/Gramophone/issues/37#issuecomment-1837493118

**Comment by nift4** [comment]
can you make a comparision video? a couple of _seconds_ should absolutely not be happening. I believe it might be related to covers now loading successfully and taking a lot of CPU time and the fact that we changed the splash screen to exit before loading library is complete

**Comment by Porkepix** [comment]
It's supposed to have a splash screen? Because I never saw any splash screen and pop directly to the main library screen.
My release of Android doesn't have the native feature to record screen, and there's nothing good for that in F-droid, so it would be difficult.

**Comment by Porkepix** [comment]
@AkaneTan I don't know what else I can provide? You talked about a splash screen, but I absolutely never saw a splash screen in Gramophone.

**Comment by AkaneTan** [comment]
> @AkaneTan I don't know what else I can provide? You talked about a splash screen, but I absolutely never saw a splash screen in Gramophone.

Hi, now I understand your situation with @nift4, can you tell me how many songs do you have in your phone?

**Comment by Porkepix** [comment]
> > @AkaneTan I don't know what else I can provide? You talked about a splash screen, but I absolutely never saw a splash screen in Gramophone.
> 
> Hi, now I understand your situation with @nift4, can you tell me how many songs do you have in your phone?

Currently 840, all of them located on the SD card. And it takes like 1-2s to move from "shows I have 0 songs" to show them all at once.

**Comment by Porkepix** [comment]
So, what did you understand from the situation @AkaneTan ?

**Comment by nift4** [comment]
we will first port splash screen to old android versions and if the issue still happens without racy ui initialization, please let us know

**Comment by nift4** [comment]
[Gramophone-1.0.2.f01579-release.zip](https://github.com/AkaneTan/Gramophone/files/14069795/Gramophone-1.0.2.f01579-release.zip)
Hi, please try this version, library loading was optimized

**Comment by Porkepix** [comment]
> [Gramophone-1.0.2.f01579-release.zip](https://github.com/AkaneTan/Gramophone/files/14069795/Gramophone-1.0.2.f01579-release.zip) Hi, please try this version, library loading was optimized

Looks like there isn't any change, unfortunately.

**Comment by nift4** [comment]
that's weird, it seems like there's some conflict with your device firmware - this version can load 20000 songs (with album art embedded) in about 0.7 seconds in the emulator.

**Comment by Porkepix** [comment]
> that's weird, it seems like there's some conflict with your device firmware - this version can load 20000 songs (with album art embedded) in about 0.7 seconds in the emulator.

Does it load something on every start or does it use some db/cache file?
Songs are located on a SD card, maybe the db/cache too: the iops of a SD card can be drastically lower than internal memory or your emulator's.

Note though that, as said in the first comment, version 1.0.1 had instant load, this is a change that happened from 1.0.2.

**Comment by nift4** [comment]
It queries data from Android's internal cache. During optimization, I noticed significant time spent on sorting, and indeed 1.0.1 had simple ASCII sorting while 1.0.2 has proper English language sorting with respect to numbers and ignoring capitalization. I will check if this is a bottleneck.

**Comment by Porkepix** [comment]
> It queries data from Android's internal cache. During optimization, I noticed significant time spent on sorting, and indeed 1.0.1 had simple ASCII sorting while 1.0.2 has proper English language sorting with respect to numbers and ignoring capitalization. I will check if this is a bottleneck.

Some of my songs also include Japanese characters besides latin but non-English (accentuated letters for example) ones, if that may have any negative effect (or require additional testing).
But Android or frameworks doesn't provide built-in sorting for any UTF-8 character? I'm quite surprised if every developer got to rewrite and implement their own sorting algorithm.

**Comment by nift4** [comment]
The sorting uses locale specific Java Collator class, so depending on phone language, sorting will change, that's what I meant. Japanese characters don't impact performance.
