### ISSUE TITLE
[FR] Support for play next when shuffle

### ISSUE THREAD

**Issue by HotarunIchijou** [FoedusProgramme/Gramophone#57]
Play next isn't available when shuffle is enabled so It's literally doesn't makes sense

https://github.com/AkaneTan/Gramophone/assets/113282550/432e91d1-b0d3-49e7-8f6a-2ec78336589d

**Comment by wolf-yuan-6115** [comment]
I think it's possible to make two playing queues, one is play next queue and one is normal playing queue. You can see Spotify's implementation on their desktop app.
