### ISSUE TITLE
Auto - pause music when earphones are disconnected.

### ISSUE THREAD

**Issue by its-pradeeps** [FoedusProgramme/Gramophone#58]
**Is your feature request related to a problem? Please describe.**
When playing music and disconnecting a wired or Bluetooth earphones, the music does not pause by itself and continues to play.
I would like the music to stop, because the moment i disconnect my earphones the song will play from my phone's speaker.

**Comment by its-pradeeps** [comment]
Hey @AkaneTan , any timeline if possible when this feature will be implemented. 
Thanks in advance.

**Comment by AkaneTan** [comment]
Implemented in 2c8faac3de071e1f90889bf6f73a649ae9b137ee.
