### ISSUE TITLE
SD CARD AUDIO FILE NOT INDXING[BUG]

### ISSUE THREAD

**Issue by AdityaMishra135** [FoedusProgramme/Gramophone#63]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nift4** [comment]
what android version / phone, the template exists for a reason

**Comment by Ashvith10** [comment]
@nift4 can I reopen a new issue related to this?

**Comment by nift4** [comment]
yes
