### ISSUE TITLE
Manage & Add your playlist

### ISSUE THREAD

**Issue by hitwonder** [FoedusProgramme/Gramophone#65]
**Is your feature request related to a problem? Please describe.**
- Manage & Add your playlist
I am currently experiencing difficulties creating new playlists or adding songs to existing playlists. Could you please provide information on when this feature will be implemented or if there are any updates on its availability?

Thanks in advance.

**Comment by AkaneTan** [comment]
Hi, this feature will be implemented in the next github stable release.

**Comment by hitwonder** [comment]
Thanks for the update. Are there any plans to release a stable version on GitHub this month, or is there information available regarding the anticipated release date?

**Comment by nift4** [comment]
@hitwonder This month implies in the next 10 days, that won't be ready by then

**Comment by hitwonder** [comment]
@nift4 Ok Thanks.

**Comment by hitwonder** [comment]
Hi, @nift4 Any update on this?

**Comment by nift4** [comment]
There are no updates currently. Closing in favor of #27
