### ISSUE TITLE
[BUG]歌曲详细信息中的文件路径显示不了

### ISSUE THREAD

**Issue by sianqin** [FoedusProgramme/Gramophone#68]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AkaneTan** [comment]
Resolved in commit 816eddfeb3a38ea8821a334a89ce5a36d4cab64f.
