### ISSUE TITLE
[BUG] if no lyrics found, (swipe down shows blank screen instead of mini player)

### ISSUE THREAD

**Issue by Eliya-Manoj** [FoedusProgramme/Gramophone#70]
https://github.com/AkaneTan/Gramophone/assets/90308888/87a307c3-81d4-4465-b0bf-b709875483fa

**Comment by AkaneTan** [comment]
Already fixed in previous commits. Will include the fix in the next release at [my telegram channel](https://t.me/AkaneDistribution)
