### ISSUE TITLE
[BUG] Only shows synched lyrics

### ISSUE THREAD

**Issue by Eliya-Manoj** [FoedusProgramme/Gramophone#71]
Non-synched lyrics are not shown [ Embedded Lyrics ].

Gramophone -

 https://github.com/AkaneTan/Gramophone/assets/90308888/d1a0df24-4088-4185-bd22-d33b86a00c9b

Other player - ![Screenshot_20231231-233321_Symphony.jpg](https://github.com/AkaneTan/Gramophone/assets/90308888/b8f0b4f6-6ce4-4494-8c3b-83c400722403)

![Screenshot_20231231-233147_Musicolet.jpg](https://github.com/AkaneTan/Gramophone/assets/90308888/2b854222-de51-4c93-ac6c-49766c585906)

**Comment by AkaneTan** [comment]
It's not a bug and since there's a lot of controversies in un-synced lyric's format, support for it won't be added.
