### ISSUE TITLE
[BUG]Gradle Sync fail

### ISSUE THREAD

**Issue by LiPolymer** [FoedusProgramme/Gramophone#74]
**Describe the bug**
Gradle project synth failed
**To Reproduce**
1. Clone this repository
2. Open it with Android Studio Iguana (Latest beta version)
3. Start Gradle Sync

**Expected behavior**
Gradle Project Sync successed

**Screenshots**
![image](https://github.com/AkaneTan/Gramophone/assets/110595296/e2af685a-be4e-4355-aefd-1fe5978f694a)
**Additional context**
Maybe it's the *.gitignore* causing the problem
![image](https://github.com/AkaneTan/Gramophone/assets/110595296/ea909283-5490-4078-80a3-38f340b11417)
Thank you😋

**Comment by nift4** [comment]
write `releaseType=test` (or any other release type, shown in about) into package.properties

**Comment by LiPolymer** [comment]
> write `releaseType=test` (or any other release type, shown in about) into package.properties

It worked.
Thank you very much 😋

**Comment by LiPolymer** [comment]
By the way,`test` needs to be in quotation marks as a string 😊 (`releaseType="test"`)
