### ISSUE TITLE
No squiggly/wavy seekbar

### ISSUE THREAD

**Issue by ghost** [FoedusProgramme/Gramophone#77]
**Describe the bug**
The only reason I wanted to use Gramophone tbh. The seekbar was promised to be squiggly, as shown by the screenshots I've seen. But when I open the app, it's very bland and there is no wavy seekbar.

**To Reproduce**
1. Just play the music.

**Expected behavior**
Squiggly/wavy seekbar

**Screenshots**
![Screenshot_2024-01-16-21-18-52-30_7b63ba6ba855e67dd5ee1b08e9300b77.jpg](https://github.com/AkaneTan/Gramophone/assets/135055975/18997cc9-69a8-44b0-9200-952adfea4fe6)

**Smartphone (please complete the following information):**
 - Device: realme Narzo 50A
 - OS: Android 13
 - Browserv Chrome
 - Version: Don't know but I don't think this matters

**Additional context**
The app really looks blander than advertised. Am I doing something wrong?

**Comment by nift4** [comment]
yes version of app did matter, squiggly seekbar is only available in beta version: https://github.com/AkaneTan/Gramophone/files/13538499/Gramophone-1.0.2.bd8ec5-release.apk.zip

**Comment by ghost** [comment]
> yes version of app did matter, squiggly seekbar is only available in beta version: https://github.com/AkaneTan/Gramophone/files/13538499/Gramophone-1.0.2.bd8ec5-release.apk.zip

I felt it was asking for browser version, I'm sorry.

**Comment by nift4** [comment]
> I felt it was asking for browser version, I'm sorry.

I adjusted the bug report template, thanks for the feedback.
