### ISSUE TITLE
Can't close app/control via notification panel

### ISSUE THREAD

**Issue by ghost** [FoedusProgramme/Gramophone#78]
**Describe the bug**
Media controls don't appear in notification panel and even when app is closed it keeps playing music.

**To Reproduce**
1. Close app while playing music.
2. Check notification panel.

**Expected behavior**
Can control songs via notifpanel or atleast stop playing music once app is closed from recents (not minimised)

**Screenshots**
![Screenshot_2024-01-16-21-26-41-89_7b63ba6ba855e67dd5ee1b08e9300b77.jpg](https://github.com/AkaneTan/Gramophone/assets/135055975/cee755a7-655a-4813-aff4-376c2a998b3f)

**Smartphone (please complete the following information):**
 - Device: Realme Narzo 50A
 - OS: Android 13
 - App Version: 1.0.2.bd8ec5

**Comment by nift4** [comment]
Hi, it works fine on AOSP ROM, Google Pixel, Motorola, I believe this issue is specific to Realme and pretty hard to fix without ColorOS smartphone.

The app continuing to play after being swiped from recents is intended behaviour by latest google design guidelines

**Comment by ghost** [comment]
@nift4 
On the non-beta version on Github, there are buttons through which I can control the music. I think there might be something up with that.

Also, if you get it to work, maybe adding an X button that closes the app would be cool, like YTM or Spotify.

**Comment by nift4** [comment]
Oh, that's interesting, I'll add this to the backlog then

**Comment by nift4** [comment]
![telegram-cloud-photo-size-5-6228850452615772478-y](https://github.com/AkaneTan/Gramophone/assets/36458596/197db855-1f9e-44bf-8a06-fb15b3d5807a)
confirmed to work in coloros 14
