### ISSUE TITLE
App crash after hitting next during a song playing

### ISSUE THREAD

**Issue by ghost** [FoedusProgramme/Gramophone#79]
**Describe the bug**
Skipping to next track during playing song crashes the app.

**To Reproduce**
1. Play a song.
2. Hit next.

**Expected behavior**
Skips to next song.

**Screenshots**
https://github.com/AkaneTan/Gramophone/assets/135055975/87e2488b-019e-4cd8-b201-46f7ed6e4c1f

![Screenshot_2024-01-17-16-00-36-38_7b63ba6ba855e67dd5ee1b08e9300b77.jpg](https://github.com/AkaneTan/Gramophone/assets/135055975/e767e3df-cd65-4ee1-a7df-291c7cdce03d)

**Smartphone (please complete the following information):**
 - Device: realme Narzo 50A
 - OS: Android 12
 - App Version: 1.0.2.d3d77b

**Comment by ghost** [comment]
edited to add screenshot of log

**Comment by nift4** [comment]
should be fixed
