### ISSUE TITLE
Debug builds

### ISSUE THREAD

**Issue by owenconnorz** [FoedusProgramme/Gramophone#80]
Please add debug builds on github actions.

Better for testing every build before the released version for finding bugs and reporting them asap also to test any new features that may be added.

**Comment by jxstavasy** [comment]
@owencz1998 there's the beta
it's sent and tested on the Telegram group
ik I'm neither Akane nor Nick but this is what happens
GitHub gets updates a bit later

**Comment by owenconnorz** [comment]
Ohh OK but is the beta updated regularly mate

**Comment by jxstavasy** [comment]
@owencz1998 every once in a while we get one, but Akane is currently out bc of university entrance test, so Nick is now responsible.
as for regularity of updates, idk

**Comment by owenconnorz** [comment]
OK thanks for your help mate 👍

**Comment by nift4** [comment]
It's planned once the development cycle gets more regular (ie after next release)

**Comment by jxstavasy** [comment]
@nift4 cool🫶🏻
