### ISSUE TITLE
Auto - pause music when Bluetooth earphones are disconnected.

### ISSUE THREAD

**Issue by its-pradeeps** [FoedusProgramme/Gramophone#82]
In the implementation of the issue: https://github.com/AkaneTan/Gramophone/issues/58 the music does not stop when <b>Bluetooth</b> earphones are disconnected.
Please implement the feature where the music stops playing when <b>Bluetooth earphones are disconnected</b>.

**Comment by AkaneTan** [comment]
Already implemented in e2a3a06e2228da966a72fdc3ca67f543706e19f6
