### ISSUE TITLE
[FR] Configure order of tabs and more theming colors

### ISSUE THREAD

**Issue by imshinyu** [FoedusProgramme/Gramophone#83]
**Is your feature request related to a problem? Please describe.**
for me i use the main "Songs" tab and "Playlists" and "Folders" so i don't care about other but "Playlists" and "Folders" are the last tabs so its kinda annoying to swipe just to go to them or swipe left and select with the list menu.
as for the colors personally i don't mind the default but it would be better to be able to choose

**Describe the solution you'd like**
ability to change the order of tabs and an option to change the color of the app

**Comment by philippkosarev** [comment]
I agree, it would improve ease of use for the app.
I have found that [LibreTube](https://github.com/libre-tube/LibreTube) does a similar thing with their navigation bar. This can be used as a reference of how the setting might look.
![LibreTube_Example-c](https://github.com/AkaneTan/Gramophone/assets/102914158/dc22c2cd-f5f3-4c0e-9d81-c5e50e6d06c0)

**Comment by qumuq-til** [comment]
I also second that request. For me it's important to land on a specific tab ('Filesystem') right from the start, because my library is organized around the filesystem and most of the audio files are untagged.

**Comment by unoukujou** [comment]
I came here to ask the same thing.

Need to hide tabs that I don't want.

And sort the tabs in the order I want.

Thanks

**Comment by nift4** [comment]
Tab order changing has been implemented.
Theming colors for <=Android S is not planned for now.
