### ISSUE TITLE
[BUG] Background Playing 

### ISSUE THREAD

**Issue by saltsoftdrink** [FoedusProgramme/Gramophone#85]
Even if the app is closed it should continue the playback please take a look a Metro Music Player app they have fixed this try to take inspiration from them
Thank You ❤️

**Comment by nift4** [comment]
Please send:
- app version
- android version
- phone model
- screen record of the issue
because Gramophone supports this just fine

**Comment by saltsoftdrink** [comment]
> Please send:
> 
>     * app version
> 
>     * android version
> 
>     * phone model
> 
>     * screen record of the issue
>       because Gramophone supports this just fine

- 1.0.3.7d1f58
- Android 13
- RMX3471
- Screen recording can not possible to upload from mobile to GitHub

**Comment by nift4** [comment]
you can .zip the file, use https://workupload.com or join our telegram chat

**Comment by saltsoftdrink** [comment]
> you can .zip the file, use https://workupload.com or join our telegram chat

There is no option for me chat on telegram

**Comment by nift4** [comment]
@saltsoftdrink then use workupload

**Comment by saltsoftdrink** [comment]
@nift4 I've a question which library did you used for seekbar/progress bar and how did you add different design play/pause btn please can you please provide the file and line number to understand both thing

**Comment by nift4** [comment]
we didn't use any library for seekbar, https://github.com/AkaneTan/Gramophone/blob/beta/app/src/main/kotlin/org/akanework/gramophone/ui/components/FullBottomSheet.kt#L1143.

closing because ot, if you eventually do want the bug fixes please upload a video to workupload.com and send the link here...

**Comment by saltsoftdrink** [comment]
> we didn't use any library for seekbar, https://github.com/AkaneTan/Gramophone/blob/beta/app/src/main/kotlin/org/akanework/gramophone/ui/components/FullBottomSheet.kt#L1143.
> 
> closing because ot, if you eventually do want the bug fixes please upload a video to workupload.com and send the link here...

Sorry for not uploading it but now I'm interested in the seekbar please can you gimme a Lil guide or resource from where I can learn please

**Comment by nift4** [comment]
https://github.com/AkaneTan/Gramophone/blob/beta/app/src/main/kotlin/org/akanework/gramophone/ui/components/SquigglyProgress.kt
