### ISSUE TITLE
[BUG] album cover too big

### ISSUE THREAD

**Issue by ghost** [FoedusProgramme/Gramophone#88]
**Describe the bug**
The album cover are too big 

**To Reproduce**
1.Install the app

**Screenshots**
![Screenshot_2024-02-17-23-01-20-709_org akanework gramophone](https://github.com/AkaneTan/Gramophone/assets/97671414/5e178518-0f5b-4fa1-8a1b-75c51db575ad)

Compere to original screenshot from github
![screenshot_2](https://github.com/AkaneTan/Gramophone/assets/97671414/edcf69ed-405e-4ae7-aba7-905e63dec3f4)

**Smartphone**
 - Device: Redmi 9a
 - OS: Android 10 miui 12
 - App Version: 1.0.3

**Additional context**
The resolution of phone is 164.9 x 77.1 x 9 mm (6.49 x 3.04 x 0.35 in) I think is enough

**Comment by AkaneTan** [comment]
Fixed in a722e08a448e97eadd06d40e0a2de1a2b0552e3f, please kindly wait for next release.

**Comment by ghost** [comment]
Thanks
