### ISSUE TITLE
[BUG] mp4 music playing without sound

### ISSUE THREAD

**Issue by SpiritOTHawk** [FoedusProgramme/Gramophone#89]
**Describe the bug**
mp4 music playing without sound.

**To Reproduce**
1. Play any music in .mp4 format

**Screenshots**
![imgbug](https://i.ibb.co/Pr6nK70/Screenshot-20240218-102211.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. NothingPhone1]
 - OS: [e.g. Android 14, NOS 2.5.2]
 - App Version: [e.g. 1.0.3]

**Comment by nift4** [comment]
I have played a song in audio/mp4 format and sound was decoded fine.

**Comment by SpiritOTHawk** [comment]
> I have played a song in audio/mp4 format and sound was decoded fine.

Hmm. File's not damaged, the music plays fine in another app.
[I don't know if I can upload the file here. But I'm upload with autoremove in a month.](https://upload.disroot.org/r/SmC1Gjhb#FyBqeXeOsZPba4bQ/DACQEZPIGF5/aGFqgQa5R0M2fM=)

**Comment by nift4** [comment]
This issue can't be fixed by Gramophone, as it depends on Android's audio codec. We don't ship ffmpeg-based codecs in Gramophone. I recommend transmuxing/transcoding your file with ffmpeg.
