### ISSUE TITLE
[BUG] going to homescreen when swiping back

### ISSUE THREAD

**Issue by HotarunIchijou** [FoedusProgramme/Gramophone#9]
**Describe the bug**
When I swiping back from player page, I'm going to homescreen instead of home page

Example
https://mega.nz/file/cyIiSBaD#Mmb0RQGP1Gb7VfSvr1pViTk_1f39YLo34V3m_OrAm_k

**Comment by AkaneTan** [comment]
That's an expected behavior. You're still in homepage but rather have navigated viewpager.

**Comment by nift4** [comment]
@AkaneTan thats weird tbh

**Comment by AkaneTan** [comment]
Ah wait I'm misunderstanding something here. Will check it tomorrow.

**Comment by AkaneTan** [comment]
Fixed in 675066f7da0379ae82a218ff4ee8940fd7dd3ff8 and 28b91371fced2cf080ac910b8cac3b0113f558ef. Closing this issue.
