### ISSUE TITLE
[BUG] SeekBarPreference summary is missing in Settings > Behavior

### ISSUE THREAD

**Issue by Porkepix** [FoedusProgramme/Gramophone#90]
**Describe the bug**
SeekBarPreference summary is missing in Settings > Behavior

**To Reproduce**

Go into Settings > Behavior
See that the MediaStore filter have no summary shown

**Expected behavior**
The summary defined at [SeekBarPreference](https://github.com/AkaneTan/Gramophone/blob/1.0.4.1/app/src/main/res/xml/settings_behavior.xml#L29) should be visible.

Also note that https://github.com/AkaneTan/Gramophone/blob/1.0.4.1/app/src/main/res/values/strings.xml#L67 would probably needs a slight rephrase (ie. removing "are"), note than I'm not a native English speaker, though.

**Screenshots**

<details>
<summary>
Screenshot
</summary>

![Screenshot_20240219-165703](https://github.com/AkaneTan/Gramophone/assets/709500/d15d87fd-ac14-446f-8cba-e85b1d1c8c95)

</details>

**Smartphone (please complete the following information):**
 - Device: Xperia XZ
 - OS: Android 8.0 (Oreo)
 - App Version: 1.0.4.1

**Additional context**
I think it was visible in previous versions, but maybe it wasn't a SeekBar back then?

**Comment by AkaneTan** [comment]
I didn't find summary necessary because -- our setting page is following AOSP settingslib's design and layout. There's no summary present in any of the aosp seekbar preferences, therefore making summary gone is **on purpose**. Also no plan on using those layouts in other apps. Closing this issue.

**Comment by nift4** [comment]
I'll rephrase the preference name and remove the unused string

**Comment by Porkepix** [comment]
> I'll rephrase the preference name and remove the unused string

Yeah that seems needed I think: while one could guess a little, I was helped by remembering seeing it in the past. Current state isn't that obvious.
(Also, not setting a maximum looks better to me? But that definitely wouldn't be possible on a SeekBar).
