### ISSUE TITLE
[BUG] Cover does not display correctly

### ISSUE THREAD

**Issue by CyanTsuki** [FoedusProgramme/Gramophone#91]
**Describe the bug**
Albums and songs don't show the correct cover. They always show the cover of the first song on the album.

**Expected behavior**
Correctly display the cover of each song and use cover.jpg as the album cover.

**Screenshots**
Bug Screenshots:
![Screenshot_20240220-112222](https://github.com/AkaneTan/Gramophone/assets/156485400/c7e87496-6e65-4a7a-bf4f-e26879c673e2)
![IMG_20240220_112238](https://github.com/AkaneTan/Gramophone/assets/156485400/2d60f152-fae7-4ea9-83ae-94cf3ac21e45)
Expected Screenshots(Navidrome is able to display correctly): 
![Screenshot_20240220-111647](https://github.com/AkaneTan/Gramophone/assets/156485400/9dfca3e4-47b1-46df-a44e-ee9c8ab9eae8)

**Smartphone:**
 - Device: Android Phone
 - OS: Android 12
 - App Version: 1.0.4.1

**Comment by CyanTsuki** [comment]
Source files:
![Screenshot_20240220-112209](https://github.com/AkaneTan/Gramophone/assets/156485400/af0da5b6-508b-42cf-8fb2-836961d828d7)

**Comment by nift4** [comment]
I'll check if Gramophone handles covers correctly and if it's related to MediaStore..

**Comment by nift4** [comment]
Can you ZIP the folder and upload it to https://pixeldrain.com/? I've been struggling to find a reproducing album.

**Comment by CyanTsuki** [comment]
> Can you ZIP the folder and upload it to https://pixeldrain.com/? I've been struggling to find a reproducing album.

https://pixeldrain.com/u/777npJXe

**Comment by nift4** [comment]
Thank you, the issue has been adressed in commit 59c0eb0f0f9627bcad49e47b339aed18f7e7f6c6.
[Gramophone-1.0.4.1.18e5ca-release.apk.zip](https://github.com/AkaneTan/Gramophone/files/14378922/Gramophone-1.0.4.1.18e5ca-release.apk.zip)
If you still have issues, make sure "Album cover compatibility mode" is enabled in Gramophone settings :)
