### ISSUE TITLE
[BUG]  Lyrics cannot be displayed properly

### ISSUE THREAD

**Issue by Super12138** [FoedusProgramme/Gramophone#92]
**Describe the bug**
The lyrics on the lyrics interface are all crammed together (without line breaks or paragraphs), making it impossible to view them properly.

**To Reproduce**
1. Open App
2. Choose a song (with lyrics)
3. Tap the lyric view button

**Expected behavior**
Display lyrics with proper line breaks, showing the lyrics and translated lyrics on each line.

**Screenshots**
![bug](https://github.com/AkaneTan/Gramophone/assets/70494801/eebd5db8-263b-4add-b1b7-1727300d59f7)

**Smartphone (please complete the following information):**
 - Device: HUAWEI P30
 - OS: HarmonyOS 4 (AOSP 10)
 - App Version: 1.0.4.1 (GitHub Release)

**Additional context**
I also tested it on AOSP and other devices, and the same issue occurs.

**Comment by nift4** [comment]
https://github.com/AkaneTan/Gramophone/files/14334826/Gramophone-1.0.4.1.c72ab5-release.apk.zip
