### ISSUE TITLE
[FR] Feature request

### ISSUE THREAD

**Issue by Lucky390163** [FoedusProgramme/Gramophone#95]
Can you add Pure Amoled theme and gradient blur theme.

And please add a synced lyrics catch, which highlights the words, too.

And very important lyrics or tag editor.

**Comment by AkaneTan** [comment]
No

**Comment by AkaneTan** [comment]
multiple theme support will NOT be added as that's very redundant and it destroys app design consistency (which already is shit right now).
We already added synced lyric support.
