### ISSUE TITLE
[BUG] app not launching

### ISSUE THREAD

**Issue by Pauler221** [FoedusProgramme/Gramophone#97]
**Describe the bug**
App crashes immediately after launch showing the crash log. 

**To Reproduce**
Open app

**Expected behavior**
App launching

**Screenshots**
![Screenshot_20240221-181943_1](https://github.com/AkaneTan/Gramophone/assets/33235963/7d0d16ca-ada1-48d5-a55a-cc50381c71e7)

**Smartphone:
 - Device: Pixel 6a
 - OS: GrapheneOS (Android 14)
 - App Version: 

version 1.0.4.1

org.akanework.gramophone
versionCode 6

targetSdk 34
minSdk 21

**Comment by nift4** [comment]
Please try to clear Gramophone's app data

**Comment by Pauler221** [comment]
> Please try to clear Gramophone's app data

This solved the issue. 

Should've tried that earlier thanks!:)

**Comment by nift4** [comment]
This issue can occur when the app is forcibly closed during saving settings. I'll make sure that it discards invalid data instead of crashing.
